export const DEFAULT_ACTION = 'app/UpdateApi/DEFAULT_ACTION';

export const ACTION_TYPE_UPDATE_API = {
  API_REQUEST_MADE_IN_UPDATE_API: 'API_REQUEST_MADE_IN_UPDATE_API',
  CLOSE_SNACKBAR_IN_UPDATE_API: 'CLOSE_SNACKBAR_IN_UPDATE_API',

  HANDLE_CHANGE_API_ID:'HANDLE_CHANGE_API_ID',
  FETCH_API_BY_ID: 'FETCH_API_BY_ID',
  FETCH_API_BY_ID_SUCCESS: 'FETCH_API_BY_ID_SUCCESS',
  FETCH_API_BY_ID_FAILURE: 'FETCH_API_BY_ID_FAILURE',

  HANDLE_CHANGE_API_DATA_IN_UPDATE_API: 'HANDLE_CHANGE_API_DATA_IN_UPDATE_API',

  //headers
  ADD_HEADER_IN_UPDATE_API: 'ADD_HEADER_IN_UPDATE_API',
  REMOVE_HEADER_IN_UPDATE_API: 'REMOVE_HEADER_IN_UPDATE_API',
  HANDLE_CHANGE_IN_HEADER_IN_UPDATE_API: 'HANDLE_CHANGE_IN_HEADER_IN_UPDATE_API',
  //parameters
  ADD_PARAMETER_IN_UPDATE_API: 'ADD_PARAMETER_IN_UPDATE_API',
  REMOVE_PARAMETER_IN_UPDATE_API: 'REMOVE_PARAMETER_IN_UPDATE_API',
  HANDLE_CHANGE_IN_PARAMETER_IN_UPDATE_API: 'HANDLE_CHANGE_IN_PARAMETER_IN_UPDATE_API',

  UPDATE_API: 'UPDATE_API',
  UPDATE_API_SUCCESS: 'UPDATE_API_SUCCESS',
  UPDATE_API_FAILURE: 'UPDATE_API_FAILURE',

  CLEAR_API_DATA_IN_UPDATE_API:'CLEAR_API_DATA_IN_UPDATE_API'
};
