export const DEFAULT_ACTION = 'app/BotList/DEFAULT_ACTION';

export const ACTION_TYPE_BOT_LIST = {
  FETCH_BOT_LIST_IN_BOT: 'FETCH_BOT_LIST_IN_BOT',
  FETCH_BOT_LIST_IN_BOT_SUCCESS: 'FETCH_BOT_LIST_IN_BOT_SUCCESS',
  FETCH_BOT_LIST_IN_BOT_FAILURE: 'FETCH_BOT_LIST_IN_BOT_FAILURE',

  FETCH_BOT_VERSION: 'FETCH_BOT_VERSION',
  FETCH_BOT_VERSION_SUCCESS: 'FETCH_BOT_VERSION_SUCCESS',
  FETCH_BOT_VERSION_FAILURE: 'FETCH_BOT_VERSION_FAILURE',

  ENABLE_BOT_SETTING: 'ENABLE_BOT_SETTING',
  ENABLE_BOT_SETTING_SUCCESS: 'ENABLE_BOT_SETTING_SUCCESS',
  ENABLE_BOT_SETTING_FAILURE: 'ENABLE_BOT_SETTING_FAILURE',

  PUBLISH_BOT_VERSION: 'PUBLISH_BOT_VERSION',
  PUBLISH_BOT_VERSION_SUCCESS: 'PUBLISH_BOT_VERSION_SUCCESS',
  PUBLISH_BOT_VERSION_FAILURE: 'PUBLISH_BOT_VERSION_FAILURE',

  TOGGLE_RETRAIN_LOADER: 'TOGGLE_RETRAIN_LOADER',
  RETRAIN_BOT_SETTING: 'RETRAIN_BOT_SETTING',
  RETRAIN_BOT_SETTING_SUCCESS: 'RETRAIN_BOT_SETTING_SUCCESS',
  RETRAIN_BOT_SETTING_FAILURE: 'RETRAIN_BOT_SETTING_FAILURE',

  TOGGLE_CREATE_BOT_MODAL: 'TOGGLE_CREATE_BOT_MODAL',

  UPLOAD_BOT_SETTING_IMAGE: 'UPLOAD_BOT_SETTING_IMAGE',
  UPLOAD_BOT_SETTING_IMAGE_SUCCESS: 'UPLOAD_BOT_SETTING_IMAGE_SUCCESS',
  UPLOAD_BOT_SETTING_IMAGE_FAILURE: 'UPLOAD_BOT_SETTING_IMAGE_FAILURE',

  CREATE_BOT: 'CREATE_BOT',
  CREATE_BOT_SUCCESS: 'CREATE_BOT_SUCCESS',
  CREATE_BOT_FAILURE: 'CREATE_BOT_FAILURE',

  CLEAR_BOT_LIST: 'CLEAR_BOT_LIST',

  CLOSE_SNACKBAR_IN_BOT: 'CLOSE_SNACKBAR_IN_BOT',

  GET_ALL_BOT: 'GET_ALL_BOT',
  GET_ALL_BOT_SUCCESS: 'GET_ALL_BOT_SUCCESS',
  GET_ALL_BOT_FAILURE: 'GET_ALL_BOT_FAILURE',

  GET_NEXT_PAGE_BOT: 'GET_NEXT_PAGE_BOT',
  GET_NEXT_PAGE_BOT_SUCCESS: 'GET_NEXT_PAGE_BOT_SUCCESS',
  GET_NEXT_PAGE_BOT_FAILURE: 'GET_NEXT_PAGE_BOT_FAILURE',

  FETCH_PROJECT_DETAILS: 'FETCH_PROJECT_DETAILS',
  FETCH_PROJECT_DETAILS_SUCCESS: 'FETCH_PROJECT_DETAILS_SUCCESS',
  FETCH_PROJECT_DETAILS_FAILURE: 'FETCH_PROJECT_DETAILS_FAILURE',

  FETCH_TEAMS: 'FETCH_TEAMS',
  FETCH_TEAMS_SUCCESS: 'FETCH_TEAMS_SUCCESS',
  FETCH_TEAMS_FAILURE: 'FETCH_TEAMS_FAILURE',
  // fetch Modal
  FETCH_MODAL_DATA: 'FETCH_MODAL_DATA',
  FETCH_MODAL_DATA_SUCCESS: 'FETCH_MODAL_DATA_SUCCESS',
  FETCH_MODAL_DATA_FAILURE: 'FETCH_MODAL_DATA_FAILURE',
};
