export const DEFAULT_ACTION = 'app/CreateApi/DEFAULT_ACTION';

export const ACTION_TYPE_CREATE_API = {
  API_REQUEST_MADE_IN_CREATE_API: 'API_REQUEST_MADE_IN_CREATE_API',
  CLOSE_SNACKBAR_IN_CREATE_API: 'CLOSE_SNACKBAR_IN_CREATE_API',

  HANDLE_CHANGE_API_DATA: 'HANDLE_CHANGE_API_DATA',

  //headers
  ADD_HEADER: 'ADD_HEADER',
  REMOVE_HEADER: 'REMOVE_HEADER',
  HANDLE_CHANGE_IN_HEADER: 'HANDLE_CHANGE_IN_HEADER',
  //parameters
  ADD_PARAMETER: 'ADD_PARAMETER',
  REMOVE_PARAMETER: 'REMOVE_PARAMETER',
  HANDLE_CHANGE_IN_PARAMETER: 'HANDLE_CHANGE_IN_PARAMETER',

  CREATE_API: 'CREATE_API',
  CREATE_API_SUCCESS: 'CREATE_API_SUCCESS',
  CREATE_API_FAILURE: 'CREATE_API_FAILURE',

  CLEAR_API_DATA:'CLEAR_API_DATA'
};
