/*
 *
 * ImportedIntentList constants
 *
 */

export const DEFAULT_ACTION = 'app/ImportedIntentList/DEFAULT_ACTION';

export const ACTION_TYPE_IMPORTED_INTENT_LIST = {
  CLOSE_SNACKBAR: 'CLOSE_SNACKBAR',

  FETCH_IMPORTED_INTENTS: 'FETCH_IMPORTED_INTENTS',
  FETCH_IMPORTED_INTENTS_SUCCESS: 'FETCH_IMPORTED_INTENTS_SUCCESS',
  FETCH_IMPORTED_INTENTS_FAILURE: 'FETCH_IMPORTED_INTENTS_FAILURE',
};
