/*
 *
 * Settings constants
 *
 */

export const DEFAULT_ACTION = 'app/Settings/DEFAULT_ACTION';
export const SETTINGS_ACTION = {
  // fetch all settings
  FETCH_ALL_SETTINGS: 'app/Settings/FETCH_ALL_SETTINGS',
  FETCH_ALL_SETTINGS_SUCCESS: 'app/Settings/FETCH_ALL_SETTINGS_SUCCESS',
  FETCH_ALL_SETTINGS_FAILURE: 'app/Settings/FETCH_ALL_SETTINGS_FAILURE',
  // fetch languages
  FETCH_LANGUAGES: 'app/Settings/FETCH_LANGUAGES',
  FETCH_LANGUAGES_SUCCESS: 'app/Settings/FETCH_LANGUAGES_SUCCESS',
  FETCH_LANGUAGES_FAILURE: 'app/Settings/FETCH_LANGUAGES_FAILURE',
  // fetch timezones
  FETCH_TIMEZONES: 'app/Settings/FETCH_TIMEZONES',
  FETCH_TIMEZONES_SUCCESS: 'app/Settings/FETCH_TIMEZONES_SUCCESS',
  FETCH_TIMEZONES_FAILURE: 'app/Settings/FETCH_TIMEZONES_FAILURE',
  // update Settings:
  UPDATE_SETTINGS: 'app/Settings/UPDATE_SETTINGS',
  UPDATE_SETTINGS_SUCCESS: 'app/Settings/UPDATE_SETTINGS_SUCCESS',
  UPDATE_SETTINGS_FAILURE: 'app/Settings/UPDATE_SETTINGS_FAILURE',

  HANDLE_CHANGE_STATE: 'app/Settings/HANDLE_CHANGE_STATE',
};
