export const DEFAULT_ACTION = 'app/FixedReply/DEFAULT_ACTION';

export const ACTION_TYPE_FIXED_REPLY = {
  FETCH_FIXED_REPLY_BY_ID: 'app/FixedReply/FETCH_FIXED_REPLY_BY_ID',
  FETCH_FIXED_REPLY_BY_ID_SUCCESS:
    'app/FixedReply/FETCH_FIXED_REPLY_BY_ID_SUCCESS',
  FETCH_FIXED_REPLY_BY_ID_FAILURE:
    'app/FixedReply/FETCH_FIXED_REPLY_BY_ID_FAILURE',

  HANDLE_CHANGE_IN_FIXED_REPLY_TITLE:
    'app/FixedReply/HANDLE_CHANGE_IN_FIXED_REPLY_TITLE',
  ADD_MATCHING_TEXT: 'app/FixedReply/ADD_MATCHING_TEXT',
  REMOVE_MATCHING_TEXT: 'app/FixedReply/REMOVE_MATCHING_TEXT',
  HANDLE_CHANGE_IN_MATCHING_TEXT:
    'app/FixedReply/HANDLE_CHANGE_IN_MATCHING_TEXT',
  HANDLE_CHANGE_IN_REPLY_TEXT: 'app/FixedReply/HANDLE_CHANGE_IN_REPLY_TEXT',
  HANDLE_CHANGE_IN_EXPIRE_DATE: 'app/FixedReply/HANDLE_CHANGE_IN_EXPIRE_DATE',

  CREATE_FIXED_REPLY: 'app/FixedReply/CREATE_FIXED_REPLY',
  CREATE_FIXED_REPLY_SUCCESS: 'app/FixedReply/CREATE_FIXED_REPLY_SUCCESS',
  CREATE_FIXED_REPLY_FAILURE: 'app/FixedReply/CREATE_FIXED_REPLY_FAILURE',

  UPDATE_FIXED_REPLY: 'app/FixedReply/UPDATE_FIXED_REPLY',
  UPDATE_FIXED_REPLY_SUCCESS: 'app/FixedReply/UPDATE_FIXED_REPLY_SUCCESS',
  UPDATE_FIXED_REPLY_FAILURE: 'app/FixedReply/UPDATE_FIXED_REPLY_FAILURE',

  CLEAR_FIXED_REPLIES: 'app/FixedReply/CLEAR_FIXED_REPLIES',

  CLOSE_SNACKBAR_IN_FIXED_REPLY: 'app/FixedReply/CLOSE_SNACKBAR_IN_FIXED_REPLY',
};
