/*
 *
 * IntentImportPage constants
 *
 */

export const DEFAULT_ACTION = 'app/IntentImportPage/DEFAULT_ACTION';

export const ACTION_TYPE_INTENT_IMPORT = {
  GET_INTENTS_BY_SOURCE: 'GET_INTENTS_BY_SOURCE',
  GET_INTENTS_BY_SOURCE_SUCCESS: 'GET_INTENTS_BY_SUCCESS',
  GET_INTENTS_BY_SOURCE_FAILURE: 'GET_INTENTS_BY_SOURCE_FAILURE',

  HANDLE_CHANGE_IN_SPECIFIC_DATA: 'HANDLE_CHANGE_IN_SPECIFIC_DATA',
  REMOVE_SPECIFIC_DATA: 'REMOVE_SPECIFIC_DATA',
  SAVE_INTENT: 'SAVE_INTENT',
  SAVE_INTENT_SUCCESS: 'SAVE_INTENT_SUCCESS',
  SAVE_INTENT_FAILURE: 'SAVE_INTENT_FAILURE',

  DISCARD_INTENT: 'DISCARD_INTENT',
  DISCARD_INTENT_SUCCESS: 'DISCARD_INTENT_SUCCESS',
  DISCARD_INTENT_FAILURE: 'DISCARD_INTENT_FAILURE',

  CLOSE_SNACKBAR: 'CLOSE_SNACKBAR',
  HANDLE_INTENT_NAME_CHANGE: 'HANDLE_INTENT_NAME_CHANGE',
};
