/*
 *
 * Navbar constants
 *
 */

export const DEFAULT_ACTION = 'app/Navbar/DEFAULT_ACTION';

export const ACTION_TYPE_MQTT = {
  CONNECTING_MQTT: 'CONNECTING_MQTT',
  ON_MESSAGE_ARRIVED: 'ON_MESSAGE_ARRIVED',
  ON_CONNECTION_LOST: 'ON_CONNECTION_LOST',
  ON_CONNECTION_FAILURE: 'ON_CONNECTION_FAILURE',
  CLEAR_NEW_ARRIVED_MESSAGE: 'CLEAR_NEW_ARRIVED_MESSAGE',
  CLEAR_CONNECTION_LOST_OBJECT: 'CLEAR_CONNECTION_LOST_OBJECT',
  ON_PUBLISH: 'ON_PUBLISH',
  ON_SUBSCRIBE: 'ON_SUBSCRIBE',
  CLEAR_NOTIFICATION_OBJ: 'CLEAR_NOTIFICATION_OBJ',
};
