export const DEFAULT_ACTION = 'app/CreateEntityModalContainer/DEFAULT_ACTION';

export const ACTION_TYPE_CREATE_ENTITY = {
  HANDLE_CHANGE_IN_ENTITY_DATA: 'HANDLE_CHANGE_ENTITY_DATA',
  CREATE_ENTITY_IN_INTENT: 'CREATE_ENTITY_IN_INTENT',
  CREATE_ENTITY_IN_INTENT_SUCCESS: 'CREATE_ENTITY_IN_INTENT_SUCCESS',
  CREATE_ENTITY_IN_INTENT_FAILURE: 'CREATE_ENTITY_IN_INTENT_FAILURE',

  HANDLE_CHANGE_SYNONYM: 'HANDLE_CHANGE_SYNONYM',
  HANDLE_CHANGE_IN_TAG_INPUT: 'HANDLE_CHANGE_IN_TAG_INPUT',
  HANDLE_CHANGE_SYNONYM_TAG: 'HANDLE_CHANGE_SYNONYM_TAG',
  REMOVE_SYNONYM: 'REMOVE_SYNONYM',
  REMOVE_SYNONYM_TAG: 'REMOVE_SYNONYM_TAG',

  HANDLE_CHANGE_REGEX: 'HANDLE_CHANGE_REGEX',
  REMOVE_REGEX: 'REMOVE_REGEX',

  CLEAR_ENTITY_DATA: 'CLEAR_ENTITY_DATA',

  CLOSE_SNACKBAR_IN_CREATE_ENTITY:'CLOSE_SNACKBAR_IN_CREATE_ENTITY'
};
