export const DEFAULT_ACTION = 'app/AutomatedReplies/DEFAULT_ACTION';

export const ACTION_TYPE_AUTOMATED_REPLIES = {
  FETCH_AUTOMATED_REPLIES: 'app/AutomatedReplies/FETCH_AUTOMATED_REPLIES',
  FETCH_AUTOMATED_REPLIES_SUCCESS:
    'app/AutomatedReplies/FETCH_AUTOMATED_REPLIES_SUCCESS',
  FETCH_AUTOMATED_REPLIES_FAILURE:
    'app/AutomatedReplies/FETCH_AUTOMATED_REPLIES_FAILURE',

  DELETE_AUTOMATED_REPLIES: 'app/AutomatedReplies/DELETE_AUTOMATED_REPLIES',
  DELETE_AUTOMATED_REPLIES_SUCCESS:
    'app/AutomatedReplies/DELETE_AUTOMATED_REPLIES_SUCCESS',
  DELETE_AUTOMATED_REPLIES_FAILURE:
    'app/AutomatedReplies/DELETE_AUTOMATED_REPLIES_FAILURE',

  UPDATE_AUTOMATED_REPLY_STATUS:
    'app/AutomatedReplies/UPDATE_AUTOMATED_REPLY_STATUS',
  UPDATE_AUTOMATED_REPLY_STATUS_SUCCESS:
    'app/AutomatedReplies/UPDATE_AUTOMATED_REPLY_STATUS_SUCCESS',
  UPDATE_AUTOMATED_REPLY_STATUS_FAILURE:
    'app/AutomatedReplies/UPDATE_AUTOMATED_REPLY_STATUS_FAILURE',

  CLEAR_AUTOMATED_REPLIES: 'app/AutomatedReplies/CLEAR_AUTOMATED_REPLIES',

  CLOSE_SNACKBAR_IN_AUTOMATED_REPLIES:
    'app/AutomatedReplies/CLOSE_SNACKBAR_IN_AUTOMATED_REPLIES',
};
