export const DEFAULT_ACTION = 'app/TryOut/DEFAULT_ACTION';

export const ACTION_TYPE_TRY_OUT = {
  API_REQUEST_MADE_IN_TRY_OUT: 'API_REQUEST_MADE_IN_TRY_OUT',

  HANDLE_CHANGE_TEXT_IN_TRY_OUT:'HANDLE_CHANGE_TEXT_IN_TRY_OUT',

  FETCH_TRY_OUT_RESPONSE: 'FETCH_TRY_OUT_RESPONSE',
  FETCH_TRY_OUT_RESPONSE_SUCCESS: 'FETCH_TRY_OUT_RESPONSE_SUCCESS',
  FETCH_TRY_OUT_RESPONSE_FAILURE: 'FETCH_TRY_OUT_RESPONSE_FAILURE',

  CLOSE_SNACKBAR_IN_TRY_OUT_PAGE: 'CLOSE_SNACKBAR_IN_TRY_OUT_PAGE',
};
