export const DEFAULT_ACTION = 'app/ResolutionReply/DEFAULT_ACTION';

export const ACTION_TYPE_RESOLUTION_REPLY = {
  HANDLE_CHANGE_IN_RESOLUTION_REPLY_TITLE:
    'app/ResolutionReply/HANDLE_CHANGE_IN_RESOLUTION_REPLY_TITLE',
  ADD_PROBLEM_DEFINITION: 'app/ResolutionReply/ADD_PROBLEM_DEFINITION',
  REMOVE_PROBLEM_DEFINITION: 'app/ResolutionReply/REMOVE_PROBLEM_DEFINITION',
  HANDLE_CHANGE_IN_PROBLEM_DEFINITION:
    'app/ResolutionReply/HANDLE_CHANGE_IN_PROBLEM_DEFINITION',

  EXPAND_PROBLEM_SOLUTION: 'app/ResolutionReply/EXPAND_PROBLEM_SOLUTION',
  MAP_PROBLEM_SOLUTION: 'app/ResolutionReply/MAP_PROBLEM_SOLUTION',
  ADD_PROBLEM_SOLUTION: 'app/ResolutionReply/ADD_PROBLEM_SOLUTION',
  REMOVE_PROBLEM_SOLUTION: 'app/ResolutionReply/REMOVE_PROBLEM_SOLUTION',
  HANDLE_CHANGE_IN_PROBLEM_SOLUTION:
    'app/ResolutionReply/HANDLE_CHANGE_IN_PROBLEM_SOLUTION',
  SAVE_PROBLEM_SOLUTION: 'app/ResolutionReply/SAVE_PROBLEM_SOLUTION',

  ADD_STEPS: 'app/ResolutionReply/ADD_STEPS',
  REMOVE_STEPS: 'app/ResolutionReply/REMOVE_STEPS',
  HANDLE_CHANGE_IN_STEPS: 'app/ResolutionReply/HANDLE_CHANGE_IN_STEPS',

  HANDLE_CHANGE_IN_FEEDBACK_TEXT:
    'app/ResolutionReply/HANDLE_CHANGE_IN_FEEDBACK_TEXT',

  FETCH_RESOLUTION_REPLY_BY_ID:
    'app/ResolutionReply/FETCH_RESOLUTION_REPLY_BY_ID',
  FETCH_RESOLUTION_REPLY_BY_ID_SUCCESS:
    'app/ResolutionReply/FETCH_RESOLUTION_REPLY_BY_ID_SUCCESS',
  FETCH_RESOLUTION_REPLY_BY_ID_FAILURE:
    'app/ResolutionReply/FETCH_RESOLUTION_REPLY_BY_ID_FAILURE',

  FETCH_SIMILAR_POSSIBLE_SOLUTIONS:
    'app/ResolutionReply/FETCH_SIMILAR_POSSIBLE_SOLUTIONS',
  FETCH_SIMILAR_POSSIBLE_SOLUTIONS_SUCCESS:
    'app/ResolutionReply/FETCH_SIMILAR_POSSIBLE_SOLUTIONS_SUCCESS',
  FETCH_SIMILAR_POSSIBLE_SOLUTIONS_FAILURE:
    'app/ResolutionReply/FETCH_SIMILAR_POSSIBLE_SOLUTIONS_FAILURE',
  CLEAR_SIMILAR_POSSIBLE_SOLUTIONS:
    'app/ResolutionReply/CLEAR_SIMILAR_POSSIBLE_SOLUTIONS',

  CREATE_RESOLUTION_REPLY: 'app/ResolutionReply/CREATE_RESOLUTION_REPLY',
  CREATE_RESOLUTION_REPLY_SUCCESS:
    'app/ResolutionReply/CREATE_RESOLUTION_REPLY_SUCCESS',
  CREATE_RESOLUTION_REPLY_FAILURE:
    'app/ResolutionReply/CREATE_RESOLUTION_REPLY_FAILURE',

  UPDATE_RESOLUTION_REPLY: 'app/ResolutionReply/UPDATE_RESOLUTION_REPLY',
  UPDATE_RESOLUTION_REPLY_SUCCESS:
    'app/ResolutionReply/UPDATE_RESOLUTION_REPLY_SUCCESS',
  UPDATE_RESOLUTION_REPLY_FAILURE:
    'app/ResolutionReply/UPDATE_RESOLUTION_REPLY_FAILURE',

  CLEAR_RESOLUTION_REPLY: 'app/ResolutionReply/CLEAR_RESOLUTION_REPLY',

  OPEN_SNACKBAR_IN_RESOLUTION_REPLY:
    'app/ResolutionReply/OPEN_SNACKBAR_IN_RESOLUTION_REPLY',
  CLOSE_SNACKBAR_IN_RESOLUTION_REPLY:
    'app/ResolutionReply/CLOSE_SNACKBAR_IN_RESOLUTION_REPLY',
};
