export const DEFAULT_ACTION = 'app/AutoTicketCreate/DEFAULT_ACTION';

export const ACTION_TYPE_TICKET_SETTING = {
  API_REQUEST_MADE_IN_TICKET_SETTING: 'API_REQUEST_MADE_IN_TICKET_SETTING',

  FETCH_TICKET_SETTING: 'FETCH_TICKET_SETTING',
  FETCH_TICKET_SETTING_SUCCESS: 'FETCH_TICKET_SETTING_SUCCESS',
  FETCH_TICKET_SETTING_FAILURE: 'FETCH_TICKET_SETTING_FAILURE',

  ENABLE_AUTO_TICKET_CREATE: 'ENABLE_AUTO_TICKET_CREATE',
  ENABLE_AUTO_TICKET_CREATE_SUCCESS: 'ENABLE_AUTO_TICKET_CREATE_SUCCESS',
  ENABLE_AUTO_TICKET_CREATE_FAILURE: 'ENABLE_AUTO_TICKET_CREATE_FAILURE',

  DISABLE_AUTO_TICKET_CREATE: 'DISABLE_AUTO_TICKET_CREATE',
  DISABLE_AUTO_TICKET_CREATE_SUCCESS: 'DISABLE_AUTO_TICKET_CREATE_SUCCESS',
  DISABLE_AUTO_TICKET_CREATE_FAILURE: 'DISABLE_AUTO_TICKET_CREATE_FAILURE',

  RETRAIN_CUSTOM_RULE: 'RETRAIN_CUSTOM_RULE',
  RETRAIN_CUSTOM_RULE_SUCCESS: 'RETRAIN_CUSTOM_RULE_SUCCESS',
  RETRAIN_CUSTOM_RULE_FAILURE: 'RETRAIN_CUSTOM_RULE_FAILURE',

  FETCH_CUSTOM_RULE: 'FETCH_CUSTOM_RULE',
  FETCH_CUSTOM_RULE_SUCCESS: 'FETCH_CUSTOM_RULE_SUCCESS',
  FETCH_CUSTOM_RULE_FAILURE: 'FETCH_CUSTOM_RULE_FAILURE',

  HANDLE_CHANGE_IN_CUSTOM_RULES: 'HANDLE_CHANGE_IN_CUSTOM_RULES',
  ADD_CUSTOM_RULE_ROW: 'ADD_CUSTOM_RULE_ROW',
  REMOVE_CUSTOM_RULE: 'REMOVE_CUSTOM_RULE',
  CLEAR_CUSTOM_RULE_MODAL: 'CLEAR_CUSTOM_RULE_MODAL',

  ADD_CUSTOM_RULE: 'ADD_CUSTOM_RULE',
  ADD_CUSTOM_RULE_SUCCESS: 'ADD_CUSTOM_RULE_SUCCESS',
  ADD_CUSTOM_RULE_FAILURE: 'ADD_CUSTOM_RULE_FAILURE',

  // FETCH_AUTO_TICKET_CREATE_IN_BOT: 'ADD_CUSTOM_RULE',
  // ADD_CUSTOM_RULE_SUCCESS: 'ADD_CUSTOM_RULE_SUCCESS',
  // ADD_CUSTOM_RULE_FAILURE: 'ADD_CUSTOM_RULE_FAILURE',

  CLOSE_SNACKBAR_IN_TICKET_SETTING_PAGE:
    'CLOSE_SNACKBAR_IN_TICKET_SETTING_PAGE',

  GET_TICKET_SETTING: 'GET_TICKET_SETTING',
  GET_TICKET_SETTING_SUCCESS: 'GET_TICKET_SETTING_SUCCESS',
  GET_TICKET_SETTING_FAILURE: 'GET_TICKET_SETTING_FAILURE',
  // fetch auto ticket
  FETCH_AUTO_TICKET_LIST: 'FETCH_AUTO_TICKET_LIST',
  FETCH_AUTO_TICKET_LIST_SUCCESS: 'FETCH_AUTO_TICKET_LIST_SUCCESS',
  FETCH_AUTO_TICKET_LIST_FAILURE: 'FETCH_AUTO_TICKET_LIST_FAILURE',

  // create auto ticket
  CREATE_AUTO_TICKET: 'CREATE_AUTO_TICKET',
  CREATE_AUTO_TICKET_SUCCESS: 'CREATE_AUTO_TICKET_SUCCESS',
  CREATE_AUTO_TICKET_FAILURE: 'CREATE_AUTO_TICKET_FAILURE',
  // update auto ticket
  UPDATE_AUTO_TICKET: 'UPDATE_AUTO_TICKET',
  UPDATE_AUTO_TICKET_SUCCESS: 'UPDATE_AUTO_TICKET_SUCCESS',
  UPDATE_AUTO_TICKET_FAILURE: 'UPDATE_AUTO_TICKET_FAILURE',
  // get auto ticket create rules
  GET_AUTO_TICKET_CREATE_RULES: 'GET_AUTO_TICKET_CREATE_RULES',
  GET_AUTO_TICKET_CREATE_RULES_SUCCESS: 'GET_AUTO_TICKET_CREATE_RULES_SUCCESS',
  GET_AUTO_TICKET_CREATE_RULES_FAILURE: 'GET_AUTO_TICKET_CREATE_RULES_FAILURE',
  // delete auto ticket create
  DELETE_AUTO_TICKET_CREATE: 'DELETE_AUTO_TICKET_CREATE',
  DELETE_AUTO_TICKET_CREATE_SUCCESS: 'DELETE_AUTO_TICKET_CREATE_SUCCESS',
  DELETE_AUTO_TICKET_CREATE_FAILURE: 'DELETE_AUTO_TICKET_CREATE_FAILURE',
  // retrain auto ticket create
  RETRAIN_AUTO_TICKET_CREATE: 'RETRAIN_AUTO_TICKET_CREATE',
  RETRAIN_AUTO_TICKET_CREATE_SUCCESS: 'RETRAIN_AUTO_TICKET_CREATE_SUCCESS',
  RETRAIN_AUTO_TICKET_CREATE_FAILURE: 'RETRAIN_AUTO_TICKET_CREATE_FAILURE',

  TOGGLE_AUTO_TICKET_CREATE_RETRAIN: 'TOGGLE_AUTO_TICKET_CREATE_RETRAIN',
};
