/*
 * AppConstants
 * Each action has a corresponding type, which the reducer knows and picks up on.
 * To avoid weird typos between the reducer and the actions, we save them as
 * constants here. We prefix them with 'yourproject/YourComponent' so we avoid
 * reducers accidentally picking up actions they shouldn't.
 *
 * Follow this format:
 * export const YOUR_ACTION_CONSTANT = 'yourproject/YourContainer/YOUR_ACTION_CONSTANT';
 */

export const LOAD_REPOS = 'boilerplate/App/LOAD_REPOS';
export const LOAD_REPOS_SUCCESS = 'boilerplate/App/LOAD_REPOS_SUCCESS';
export const LOAD_REPOS_ERROR = 'boilerplate/App/LOAD_REPOS_ERROR';
export const ACTION_TYPE_NAVBAR = {
  TOGGLE_EMPTY_SERVICE_MODAL: 'TOGGLE_EMPTY_SERVICE_MODAL',

  HANDLE_CHANGE_BREADCRUMBS_VALUE: 'HANDLE_CHANGE_BREADCRUMBS_VALUE',

  HANDLE_CHANGE_SERVICE_ID_IN_NAVBAR: 'HANDLE_CHANGE_SERVICE_ID_IN_NAVBAR',
  FETCH_SERVICE_IN_NAVBAR: 'FETCH_SERVICE_IN_NAVBAR',
  FETCH_SERVICE_IN_NAVBAR_SUCCESS: 'FETCH_SERVICE_IN_NAVBAR_SUCCESS',
  FETCH_SERVICE_IN_NAVBAR_FAILURE: 'FETCH_SERVICE_IN_NAVBAR_FAILURE',

  FETCH_PROJECT_IN_NAVBAR: 'FETCH_PROJECT_IN_NAVBAR',
  FETCH_PROJECT_IN_NAVBAR_SUCCESS: 'FETCH_PROJECT_IN_NAVBAR_SUCCESS',
  FETCH_PROJECT_IN_NAVBAR_FAILURE: 'FETCH_PROJECT_IN_NAVBAR_FAILURE',

  HANDLE_CHANGE_IN_SIDEBAR: 'HANDLE_CHANGE_IN_SIDEBAR',

  RELOAD_CONTAINER: 'RELOAD_CONTAINER',
  CLOSE_SNACKBAR: 'CLOSE_SNACKBAR',

  CLEAR_ALL_GLOBAL_STATE: 'CLEAR_ALL_GLOBAL_STATE',
};
export const ACTION_TYPE_GLOBAL_INTENT = {
  OPEN_CREATE_ENTITY_MODAL: 'OPEN_CREATE_ENTITY_MODAL',
  CLOSE_CREATE_ENTITY_MODAL: 'CLOSE_CREATE_ENTITY_MODAL',
  HANDLE_CHANGE_IN_IS_BOT_TRAINING: 'HANDLE_CHANGE_IN_IS_BOT_TRAINING',
  HANDLE_CHANGE_IN_IS_CUSTOM_RULE_TRAINING:
    'HANDLE_CHANGE_IN_IS_CUSTOM_RULE_TRAINING',

  FETCH_ENTITY_IN_INTENT: 'FETCH_ENTITY_IN_INTENT',
  FETCH_ENTITY_IN_INTENT_SUCCESS: 'FETCH_ENTITY_IN_INTENT_SUCCESS',
  FETCH_ENTITY_IN_INTENT_FAILURE: 'FETCH_ENTITY_IN_INTENT_FAILURE',

  OPEN_TRY_OUT_MODAL: 'OPEN_TRY_OUT_MODAL',
  CLEAR_TRY_OUT_DATA: 'CLEAR_TRY_OUT_DATA',
};
export const ACTION_TYPE_SERVICE = {
  OPEN_INTEGRATION_TAB_AFTER_CREATING_API:
    'OPEN_INTEGRATION_TAB_AFTER_CREATING_API',
  OPEN_BOT_TAB_AFTER_CREATING_INTENT: 'OPEN_BOT_TAB_AFTER_CREATING_INTENT',
};
export const ACTION_TYPE_EMPLOYEE = {
  FETCH_EMPLOYEE_GLOBALLY: 'FETCH_EMPLOYEE_GLOBALLY',
  FETCH_EMPLOYEE_GLOBALLY_SUCCESS: 'FETCH_EMPLOYEE_GLOBALLY_SUCCESS',
  FETCH_EMPLOYEE_GLOBALLY_FAILURE: 'FETCH_EMPLOYEE_GLOBALLY_FAILURE',

  FETCH_GENERATE_TOKENS: 'FETCH_GENERATE_TOKENS',
  FETCH_GENERATE_TOKENS_SUCCESS: 'FETCH_GENERATE_TOKENS_SUCCESS',
  FETCH_GENERATE_TOKENS_FAILURE: 'FETCH_GENERATE_TOKENS_FAILURE',
};
export const ACTION_TYPE_GLOBAL_TICKET = {
  HANDLE_CHANGE_ASSIGNED_EMPLOYEE_ID_IN_TICKET:
    'HANDLE_CHANGE_ASSIGNED_EMPLOYEE_ID_IN_TICKET',
};
export const ACTION_TYPE_USER = {
  SAVE_USER_INFORMATION: 'SAVE_USER_INFORMATION',
  SELECT_THE_MAIN_USER: 'SELECT_THE_MAIN_USER',
  // GET_SERVICE_GROUP_REQUEST: 'GET_SERVICE_GROUP_REQUEST',
  // GET_SERVICE_GROUP_SUCCESS: 'GET_SERVICE_GROUP_SUCCESS',
  // GET_SERVICE_GROUP_FAILURE: 'GET_SERVICE_GROUP_FAILURE',
};
export const ACTION_TYPE_BOT = {
  GET_ALL_BOT: 'GET_ALL_BOT',
  GET_ALL_BOT_SUCCESS: 'GET_ALL_BOT_SUCCESS',
  GET_ALL_BOT_FAILURE: 'GET_ALL_BOT_FAILURE',
};
export const SETTINGS_ACTION = {
  FETCH_ALL_SETTINGS: 'app/Settings/FETCH_ALL_SETTINGS',
  FETCH_ALL_SETTINGS_SUCCESS: 'app/Settings/FETCH_ALL_SETTINGS_SUCCESS',
  FETCH_ALL_SETTINGS_FAILURE: 'app/Settings/FETCH_ALL_SETTINGS_FAILURE',
};
