/*
 *
 * ListApi constants
 *
 */

export const DEFAULT_ACTION = 'app/ListApi/DEFAULT_ACTION';

export const ACTION_TYPE_LIST_API = {
  API_REQUEST_MADE_IN_LIST_API: 'API_REQUEST_MADE_IN_LIST_API',

  FETCH_LIST_API: 'FETCH_LIST_API',
  FETCH_LIST_API_SUCCESS: 'FETCH_LIST_API_SUCCESS',
  FETCH_LIST_API_FAILURE: 'FETCH_LIST_API_FAILURE',
  DELETE_LIST_API: 'DELETE_LIST_API',
  DELETE_LIST_API_SUCCESS: 'DELETE_LIST_API_SUCCESS',
  DELETE_LIST_API_FAILURE: 'DELETE_LIST_API_FAILURE',

  CLOSE_SNACKBAR_IN_LIST_API: 'CLOSE_SNACKBAR_IN_LIST_API',

  GET_ALL_API: 'GET_ALL_API',
  GET_ALL_API_SUCCESS: 'GET_ALL_API_SUCCESS',
  GET_ALL_API_FAILURE: 'GET_ALL_API_FAILURE',
};
