// source: account_notification.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var user_pb = require('./user_pb.js');
goog.object.extend(proto, user_pb);
var settings_pb = require('./settings_pb.js');
goog.object.extend(proto, settings_pb);
goog.exportSymbol('proto.treeleaf.anydone.entities.AccountNotification', null, global);
goog.exportSymbol('proto.treeleaf.anydone.entities.AccountNotification.ActionType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.treeleaf.anydone.entities.AccountNotification = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.treeleaf.anydone.entities.AccountNotification.repeatedFields_, null);
};
goog.inherits(proto.treeleaf.anydone.entities.AccountNotification, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.treeleaf.anydone.entities.AccountNotification.displayName = 'proto.treeleaf.anydone.entities.AccountNotification';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.treeleaf.anydone.entities.AccountNotification.repeatedFields_ = [6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.treeleaf.anydone.entities.AccountNotification.prototype.toObject = function(opt_includeInstance) {
  return proto.treeleaf.anydone.entities.AccountNotification.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.treeleaf.anydone.entities.AccountNotification} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.AccountNotification.toObject = function(includeInstance, msg) {
  var f, obj = {
    actiontype: jspb.Message.getFieldWithDefault(msg, 1, 0),
    accountid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    url: jspb.Message.getFieldWithDefault(msg, 3, ""),
    spaccountid: jspb.Message.getFieldWithDefault(msg, 4, ""),
    userstatus: (f = msg.getUserstatus()) && user_pb.UserStatus.toObject(includeInstance, f),
    settingsList: jspb.Message.toObjectList(msg.getSettingsList(),
    settings_pb.Settings.toObject, includeInstance),
    employeeprofile: (f = msg.getEmployeeprofile()) && user_pb.EmployeeProfile.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.treeleaf.anydone.entities.AccountNotification}
 */
proto.treeleaf.anydone.entities.AccountNotification.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.treeleaf.anydone.entities.AccountNotification;
  return proto.treeleaf.anydone.entities.AccountNotification.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.treeleaf.anydone.entities.AccountNotification} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.treeleaf.anydone.entities.AccountNotification}
 */
proto.treeleaf.anydone.entities.AccountNotification.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.treeleaf.anydone.entities.AccountNotification.ActionType} */ (reader.readEnum());
      msg.setActiontype(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAccountid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setSpaccountid(value);
      break;
    case 5:
      var value = new user_pb.UserStatus;
      reader.readMessage(value,user_pb.UserStatus.deserializeBinaryFromReader);
      msg.setUserstatus(value);
      break;
    case 6:
      var value = new settings_pb.Settings;
      reader.readMessage(value,settings_pb.Settings.deserializeBinaryFromReader);
      msg.addSettings(value);
      break;
    case 7:
      var value = new user_pb.EmployeeProfile;
      reader.readMessage(value,user_pb.EmployeeProfile.deserializeBinaryFromReader);
      msg.setEmployeeprofile(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.treeleaf.anydone.entities.AccountNotification.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.treeleaf.anydone.entities.AccountNotification.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.treeleaf.anydone.entities.AccountNotification} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.AccountNotification.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getActiontype();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getAccountid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getUrl();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getSpaccountid();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getUserstatus();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      user_pb.UserStatus.serializeBinaryToWriter
    );
  }
  f = message.getSettingsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      settings_pb.Settings.serializeBinaryToWriter
    );
  }
  f = message.getEmployeeprofile();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      user_pb.EmployeeProfile.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.treeleaf.anydone.entities.AccountNotification.ActionType = {
  UNKNOWN_ACTION_TYPE: 0,
  ACCOUNT_ADDED: 1,
  ACCOUNT_UPDATED: 2,
  ACCOUNT_DELETED: 3,
  USER_STATUS_UPDATED: 4,
  USER_STATUS_DELETED: 5,
  SETTING_UPDATED: 6
};

/**
 * optional ActionType actionType = 1;
 * @return {!proto.treeleaf.anydone.entities.AccountNotification.ActionType}
 */
proto.treeleaf.anydone.entities.AccountNotification.prototype.getActiontype = function() {
  return /** @type {!proto.treeleaf.anydone.entities.AccountNotification.ActionType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.treeleaf.anydone.entities.AccountNotification.ActionType} value
 * @return {!proto.treeleaf.anydone.entities.AccountNotification} returns this
 */
proto.treeleaf.anydone.entities.AccountNotification.prototype.setActiontype = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string accountId = 2;
 * @return {string}
 */
proto.treeleaf.anydone.entities.AccountNotification.prototype.getAccountid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.AccountNotification} returns this
 */
proto.treeleaf.anydone.entities.AccountNotification.prototype.setAccountid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string url = 3;
 * @return {string}
 */
proto.treeleaf.anydone.entities.AccountNotification.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.AccountNotification} returns this
 */
proto.treeleaf.anydone.entities.AccountNotification.prototype.setUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string spAccountId = 4;
 * @return {string}
 */
proto.treeleaf.anydone.entities.AccountNotification.prototype.getSpaccountid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.AccountNotification} returns this
 */
proto.treeleaf.anydone.entities.AccountNotification.prototype.setSpaccountid = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional UserStatus userStatus = 5;
 * @return {?proto.treeleaf.anydone.entities.UserStatus}
 */
proto.treeleaf.anydone.entities.AccountNotification.prototype.getUserstatus = function() {
  return /** @type{?proto.treeleaf.anydone.entities.UserStatus} */ (
    jspb.Message.getWrapperField(this, user_pb.UserStatus, 5));
};


/**
 * @param {?proto.treeleaf.anydone.entities.UserStatus|undefined} value
 * @return {!proto.treeleaf.anydone.entities.AccountNotification} returns this
*/
proto.treeleaf.anydone.entities.AccountNotification.prototype.setUserstatus = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.entities.AccountNotification} returns this
 */
proto.treeleaf.anydone.entities.AccountNotification.prototype.clearUserstatus = function() {
  return this.setUserstatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.entities.AccountNotification.prototype.hasUserstatus = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * repeated Settings settings = 6;
 * @return {!Array<!proto.treeleaf.anydone.entities.Settings>}
 */
proto.treeleaf.anydone.entities.AccountNotification.prototype.getSettingsList = function() {
  return /** @type{!Array<!proto.treeleaf.anydone.entities.Settings>} */ (
    jspb.Message.getRepeatedWrapperField(this, settings_pb.Settings, 6));
};


/**
 * @param {!Array<!proto.treeleaf.anydone.entities.Settings>} value
 * @return {!proto.treeleaf.anydone.entities.AccountNotification} returns this
*/
proto.treeleaf.anydone.entities.AccountNotification.prototype.setSettingsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.treeleaf.anydone.entities.Settings=} opt_value
 * @param {number=} opt_index
 * @return {!proto.treeleaf.anydone.entities.Settings}
 */
proto.treeleaf.anydone.entities.AccountNotification.prototype.addSettings = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.treeleaf.anydone.entities.Settings, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.treeleaf.anydone.entities.AccountNotification} returns this
 */
proto.treeleaf.anydone.entities.AccountNotification.prototype.clearSettingsList = function() {
  return this.setSettingsList([]);
};


/**
 * optional EmployeeProfile employeeProfile = 7;
 * @return {?proto.treeleaf.anydone.entities.EmployeeProfile}
 */
proto.treeleaf.anydone.entities.AccountNotification.prototype.getEmployeeprofile = function() {
  return /** @type{?proto.treeleaf.anydone.entities.EmployeeProfile} */ (
    jspb.Message.getWrapperField(this, user_pb.EmployeeProfile, 7));
};


/**
 * @param {?proto.treeleaf.anydone.entities.EmployeeProfile|undefined} value
 * @return {!proto.treeleaf.anydone.entities.AccountNotification} returns this
*/
proto.treeleaf.anydone.entities.AccountNotification.prototype.setEmployeeprofile = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.entities.AccountNotification} returns this
 */
proto.treeleaf.anydone.entities.AccountNotification.prototype.clearEmployeeprofile = function() {
  return this.setEmployeeprofile(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.entities.AccountNotification.prototype.hasEmployeeprofile = function() {
  return jspb.Message.getField(this, 7) != null;
};


goog.object.extend(exports, proto.treeleaf.anydone.entities);
