// source: global_search.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var inbox_pb = require('./inbox_pb.js');
goog.object.extend(proto, inbox_pb);
var calendar_pb = require('./calendar_pb.js');
goog.object.extend(proto, calendar_pb);
var user_pb = require('./user_pb.js');
goog.object.extend(proto, user_pb);
var ticket_pb = require('./ticket_pb.js');
goog.object.extend(proto, ticket_pb);
goog.exportSymbol('proto.treeleaf.anydone.entities.GlobalSearchRequest', null, global);
goog.exportSymbol('proto.treeleaf.anydone.entities.GlobalSearchResponse', null, global);
goog.exportSymbol('proto.treeleaf.anydone.entities.GlobalSearchType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.treeleaf.anydone.entities.GlobalSearchRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.treeleaf.anydone.entities.GlobalSearchRequest.repeatedFields_, null);
};
goog.inherits(proto.treeleaf.anydone.entities.GlobalSearchRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.treeleaf.anydone.entities.GlobalSearchRequest.displayName = 'proto.treeleaf.anydone.entities.GlobalSearchRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.treeleaf.anydone.entities.GlobalSearchResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.treeleaf.anydone.entities.GlobalSearchResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.treeleaf.anydone.entities.GlobalSearchResponse.displayName = 'proto.treeleaf.anydone.entities.GlobalSearchResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.treeleaf.anydone.entities.GlobalSearchRequest.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.treeleaf.anydone.entities.GlobalSearchRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.treeleaf.anydone.entities.GlobalSearchRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.treeleaf.anydone.entities.GlobalSearchRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.GlobalSearchRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    typeList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
    query: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.treeleaf.anydone.entities.GlobalSearchRequest}
 */
proto.treeleaf.anydone.entities.GlobalSearchRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.treeleaf.anydone.entities.GlobalSearchRequest;
  return proto.treeleaf.anydone.entities.GlobalSearchRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.treeleaf.anydone.entities.GlobalSearchRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.treeleaf.anydone.entities.GlobalSearchRequest}
 */
proto.treeleaf.anydone.entities.GlobalSearchRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var values = /** @type {!Array<!proto.treeleaf.anydone.entities.GlobalSearchType>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addType(values[i]);
      }
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setQuery(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.treeleaf.anydone.entities.GlobalSearchRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.treeleaf.anydone.entities.GlobalSearchRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.treeleaf.anydone.entities.GlobalSearchRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.GlobalSearchRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTypeList();
  if (f.length > 0) {
    writer.writePackedEnum(
      1,
      f
    );
  }
  f = message.getQuery();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * repeated GlobalSearchType type = 1;
 * @return {!Array<!proto.treeleaf.anydone.entities.GlobalSearchType>}
 */
proto.treeleaf.anydone.entities.GlobalSearchRequest.prototype.getTypeList = function() {
  return /** @type {!Array<!proto.treeleaf.anydone.entities.GlobalSearchType>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<!proto.treeleaf.anydone.entities.GlobalSearchType>} value
 * @return {!proto.treeleaf.anydone.entities.GlobalSearchRequest} returns this
 */
proto.treeleaf.anydone.entities.GlobalSearchRequest.prototype.setTypeList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {!proto.treeleaf.anydone.entities.GlobalSearchType} value
 * @param {number=} opt_index
 * @return {!proto.treeleaf.anydone.entities.GlobalSearchRequest} returns this
 */
proto.treeleaf.anydone.entities.GlobalSearchRequest.prototype.addType = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.treeleaf.anydone.entities.GlobalSearchRequest} returns this
 */
proto.treeleaf.anydone.entities.GlobalSearchRequest.prototype.clearTypeList = function() {
  return this.setTypeList([]);
};


/**
 * optional string query = 2;
 * @return {string}
 */
proto.treeleaf.anydone.entities.GlobalSearchRequest.prototype.getQuery = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.GlobalSearchRequest} returns this
 */
proto.treeleaf.anydone.entities.GlobalSearchRequest.prototype.setQuery = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.treeleaf.anydone.entities.GlobalSearchResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.treeleaf.anydone.entities.GlobalSearchResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.treeleaf.anydone.entities.GlobalSearchResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.GlobalSearchResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    inbox: (f = msg.getInbox()) && inbox_pb.Inbox.toObject(includeInstance, f),
    meet: (f = msg.getMeet()) && calendar_pb.Meet.toObject(includeInstance, f),
    account: (f = msg.getAccount()) && user_pb.Account.toObject(includeInstance, f),
    ticket: (f = msg.getTicket()) && ticket_pb.Ticket.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.treeleaf.anydone.entities.GlobalSearchResponse}
 */
proto.treeleaf.anydone.entities.GlobalSearchResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.treeleaf.anydone.entities.GlobalSearchResponse;
  return proto.treeleaf.anydone.entities.GlobalSearchResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.treeleaf.anydone.entities.GlobalSearchResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.treeleaf.anydone.entities.GlobalSearchResponse}
 */
proto.treeleaf.anydone.entities.GlobalSearchResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.treeleaf.anydone.entities.GlobalSearchType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = new inbox_pb.Inbox;
      reader.readMessage(value,inbox_pb.Inbox.deserializeBinaryFromReader);
      msg.setInbox(value);
      break;
    case 3:
      var value = new calendar_pb.Meet;
      reader.readMessage(value,calendar_pb.Meet.deserializeBinaryFromReader);
      msg.setMeet(value);
      break;
    case 4:
      var value = new user_pb.Account;
      reader.readMessage(value,user_pb.Account.deserializeBinaryFromReader);
      msg.setAccount(value);
      break;
    case 5:
      var value = new ticket_pb.Ticket;
      reader.readMessage(value,ticket_pb.Ticket.deserializeBinaryFromReader);
      msg.setTicket(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.treeleaf.anydone.entities.GlobalSearchResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.treeleaf.anydone.entities.GlobalSearchResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.treeleaf.anydone.entities.GlobalSearchResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.GlobalSearchResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getInbox();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      inbox_pb.Inbox.serializeBinaryToWriter
    );
  }
  f = message.getMeet();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      calendar_pb.Meet.serializeBinaryToWriter
    );
  }
  f = message.getAccount();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      user_pb.Account.serializeBinaryToWriter
    );
  }
  f = message.getTicket();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      ticket_pb.Ticket.serializeBinaryToWriter
    );
  }
};


/**
 * optional GlobalSearchType type = 1;
 * @return {!proto.treeleaf.anydone.entities.GlobalSearchType}
 */
proto.treeleaf.anydone.entities.GlobalSearchResponse.prototype.getType = function() {
  return /** @type {!proto.treeleaf.anydone.entities.GlobalSearchType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.treeleaf.anydone.entities.GlobalSearchType} value
 * @return {!proto.treeleaf.anydone.entities.GlobalSearchResponse} returns this
 */
proto.treeleaf.anydone.entities.GlobalSearchResponse.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional Inbox inbox = 2;
 * @return {?proto.treeleaf.anydone.entities.Inbox}
 */
proto.treeleaf.anydone.entities.GlobalSearchResponse.prototype.getInbox = function() {
  return /** @type{?proto.treeleaf.anydone.entities.Inbox} */ (
    jspb.Message.getWrapperField(this, inbox_pb.Inbox, 2));
};


/**
 * @param {?proto.treeleaf.anydone.entities.Inbox|undefined} value
 * @return {!proto.treeleaf.anydone.entities.GlobalSearchResponse} returns this
*/
proto.treeleaf.anydone.entities.GlobalSearchResponse.prototype.setInbox = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.entities.GlobalSearchResponse} returns this
 */
proto.treeleaf.anydone.entities.GlobalSearchResponse.prototype.clearInbox = function() {
  return this.setInbox(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.entities.GlobalSearchResponse.prototype.hasInbox = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Meet meet = 3;
 * @return {?proto.treeleaf.anydone.entities.Meet}
 */
proto.treeleaf.anydone.entities.GlobalSearchResponse.prototype.getMeet = function() {
  return /** @type{?proto.treeleaf.anydone.entities.Meet} */ (
    jspb.Message.getWrapperField(this, calendar_pb.Meet, 3));
};


/**
 * @param {?proto.treeleaf.anydone.entities.Meet|undefined} value
 * @return {!proto.treeleaf.anydone.entities.GlobalSearchResponse} returns this
*/
proto.treeleaf.anydone.entities.GlobalSearchResponse.prototype.setMeet = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.entities.GlobalSearchResponse} returns this
 */
proto.treeleaf.anydone.entities.GlobalSearchResponse.prototype.clearMeet = function() {
  return this.setMeet(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.entities.GlobalSearchResponse.prototype.hasMeet = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Account account = 4;
 * @return {?proto.treeleaf.anydone.entities.Account}
 */
proto.treeleaf.anydone.entities.GlobalSearchResponse.prototype.getAccount = function() {
  return /** @type{?proto.treeleaf.anydone.entities.Account} */ (
    jspb.Message.getWrapperField(this, user_pb.Account, 4));
};


/**
 * @param {?proto.treeleaf.anydone.entities.Account|undefined} value
 * @return {!proto.treeleaf.anydone.entities.GlobalSearchResponse} returns this
*/
proto.treeleaf.anydone.entities.GlobalSearchResponse.prototype.setAccount = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.entities.GlobalSearchResponse} returns this
 */
proto.treeleaf.anydone.entities.GlobalSearchResponse.prototype.clearAccount = function() {
  return this.setAccount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.entities.GlobalSearchResponse.prototype.hasAccount = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional Ticket ticket = 5;
 * @return {?proto.treeleaf.anydone.entities.Ticket}
 */
proto.treeleaf.anydone.entities.GlobalSearchResponse.prototype.getTicket = function() {
  return /** @type{?proto.treeleaf.anydone.entities.Ticket} */ (
    jspb.Message.getWrapperField(this, ticket_pb.Ticket, 5));
};


/**
 * @param {?proto.treeleaf.anydone.entities.Ticket|undefined} value
 * @return {!proto.treeleaf.anydone.entities.GlobalSearchResponse} returns this
*/
proto.treeleaf.anydone.entities.GlobalSearchResponse.prototype.setTicket = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.entities.GlobalSearchResponse} returns this
 */
proto.treeleaf.anydone.entities.GlobalSearchResponse.prototype.clearTicket = function() {
  return this.setTicket(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.entities.GlobalSearchResponse.prototype.hasTicket = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * @enum {number}
 */
proto.treeleaf.anydone.entities.GlobalSearchType = {
  UNKNOWN_SEARCH_RESPONSE_TYPE: 0,
  MESSAGE: 1,
  MEET: 2,
  DIRECT_MESSAGE: 3,
  GROUP: 4,
  MEMBER: 5,
  TICKET: 6
};

goog.object.extend(exports, proto.treeleaf.anydone.entities);
