// source: nlu_helper.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var bot_housekeeping_pb = require('./bot_housekeeping_pb.js');
goog.object.extend(proto, bot_housekeeping_pb);
goog.exportSymbol('proto.treeleaf.anydone.entities.MisleadingRequest', null, global);
goog.exportSymbol('proto.treeleaf.anydone.entities.MisleadingResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.treeleaf.anydone.entities.MisleadingRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.treeleaf.anydone.entities.MisleadingRequest.repeatedFields_, null);
};
goog.inherits(proto.treeleaf.anydone.entities.MisleadingRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.treeleaf.anydone.entities.MisleadingRequest.displayName = 'proto.treeleaf.anydone.entities.MisleadingRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.treeleaf.anydone.entities.MisleadingResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.treeleaf.anydone.entities.MisleadingResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.treeleaf.anydone.entities.MisleadingResponse.displayName = 'proto.treeleaf.anydone.entities.MisleadingResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.treeleaf.anydone.entities.MisleadingRequest.repeatedFields_ = [1,2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.treeleaf.anydone.entities.MisleadingRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.treeleaf.anydone.entities.MisleadingRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.treeleaf.anydone.entities.MisleadingRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.MisleadingRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    newtrainingphrasesList: jspb.Message.toObjectList(msg.getNewtrainingphrasesList(),
    bot_housekeeping_pb.TrainingPhrase.toObject, includeInstance),
    oldtrainingphrasesList: jspb.Message.toObjectList(msg.getOldtrainingphrasesList(),
    bot_housekeeping_pb.TrainingPhrase.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.treeleaf.anydone.entities.MisleadingRequest}
 */
proto.treeleaf.anydone.entities.MisleadingRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.treeleaf.anydone.entities.MisleadingRequest;
  return proto.treeleaf.anydone.entities.MisleadingRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.treeleaf.anydone.entities.MisleadingRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.treeleaf.anydone.entities.MisleadingRequest}
 */
proto.treeleaf.anydone.entities.MisleadingRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new bot_housekeeping_pb.TrainingPhrase;
      reader.readMessage(value,bot_housekeeping_pb.TrainingPhrase.deserializeBinaryFromReader);
      msg.addNewtrainingphrases(value);
      break;
    case 2:
      var value = new bot_housekeeping_pb.TrainingPhrase;
      reader.readMessage(value,bot_housekeeping_pb.TrainingPhrase.deserializeBinaryFromReader);
      msg.addOldtrainingphrases(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.treeleaf.anydone.entities.MisleadingRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.treeleaf.anydone.entities.MisleadingRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.treeleaf.anydone.entities.MisleadingRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.MisleadingRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNewtrainingphrasesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      bot_housekeeping_pb.TrainingPhrase.serializeBinaryToWriter
    );
  }
  f = message.getOldtrainingphrasesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      bot_housekeeping_pb.TrainingPhrase.serializeBinaryToWriter
    );
  }
};


/**
 * repeated TrainingPhrase newTrainingPhrases = 1;
 * @return {!Array<!proto.treeleaf.anydone.entities.TrainingPhrase>}
 */
proto.treeleaf.anydone.entities.MisleadingRequest.prototype.getNewtrainingphrasesList = function() {
  return /** @type{!Array<!proto.treeleaf.anydone.entities.TrainingPhrase>} */ (
    jspb.Message.getRepeatedWrapperField(this, bot_housekeeping_pb.TrainingPhrase, 1));
};


/**
 * @param {!Array<!proto.treeleaf.anydone.entities.TrainingPhrase>} value
 * @return {!proto.treeleaf.anydone.entities.MisleadingRequest} returns this
*/
proto.treeleaf.anydone.entities.MisleadingRequest.prototype.setNewtrainingphrasesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.treeleaf.anydone.entities.TrainingPhrase=} opt_value
 * @param {number=} opt_index
 * @return {!proto.treeleaf.anydone.entities.TrainingPhrase}
 */
proto.treeleaf.anydone.entities.MisleadingRequest.prototype.addNewtrainingphrases = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.treeleaf.anydone.entities.TrainingPhrase, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.treeleaf.anydone.entities.MisleadingRequest} returns this
 */
proto.treeleaf.anydone.entities.MisleadingRequest.prototype.clearNewtrainingphrasesList = function() {
  return this.setNewtrainingphrasesList([]);
};


/**
 * repeated TrainingPhrase oldTrainingPhrases = 2;
 * @return {!Array<!proto.treeleaf.anydone.entities.TrainingPhrase>}
 */
proto.treeleaf.anydone.entities.MisleadingRequest.prototype.getOldtrainingphrasesList = function() {
  return /** @type{!Array<!proto.treeleaf.anydone.entities.TrainingPhrase>} */ (
    jspb.Message.getRepeatedWrapperField(this, bot_housekeeping_pb.TrainingPhrase, 2));
};


/**
 * @param {!Array<!proto.treeleaf.anydone.entities.TrainingPhrase>} value
 * @return {!proto.treeleaf.anydone.entities.MisleadingRequest} returns this
*/
proto.treeleaf.anydone.entities.MisleadingRequest.prototype.setOldtrainingphrasesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.treeleaf.anydone.entities.TrainingPhrase=} opt_value
 * @param {number=} opt_index
 * @return {!proto.treeleaf.anydone.entities.TrainingPhrase}
 */
proto.treeleaf.anydone.entities.MisleadingRequest.prototype.addOldtrainingphrases = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.treeleaf.anydone.entities.TrainingPhrase, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.treeleaf.anydone.entities.MisleadingRequest} returns this
 */
proto.treeleaf.anydone.entities.MisleadingRequest.prototype.clearOldtrainingphrasesList = function() {
  return this.setOldtrainingphrasesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.treeleaf.anydone.entities.MisleadingResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.treeleaf.anydone.entities.MisleadingResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.treeleaf.anydone.entities.MisleadingResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.MisleadingResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    text: jspb.Message.getFieldWithDefault(msg, 1, ""),
    score: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.treeleaf.anydone.entities.MisleadingResponse}
 */
proto.treeleaf.anydone.entities.MisleadingResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.treeleaf.anydone.entities.MisleadingResponse;
  return proto.treeleaf.anydone.entities.MisleadingResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.treeleaf.anydone.entities.MisleadingResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.treeleaf.anydone.entities.MisleadingResponse}
 */
proto.treeleaf.anydone.entities.MisleadingResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setText(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setScore(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.treeleaf.anydone.entities.MisleadingResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.treeleaf.anydone.entities.MisleadingResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.treeleaf.anydone.entities.MisleadingResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.MisleadingResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getText();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getScore();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
};


/**
 * optional string text = 1;
 * @return {string}
 */
proto.treeleaf.anydone.entities.MisleadingResponse.prototype.getText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.MisleadingResponse} returns this
 */
proto.treeleaf.anydone.entities.MisleadingResponse.prototype.setText = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional double score = 2;
 * @return {number}
 */
proto.treeleaf.anydone.entities.MisleadingResponse.prototype.getScore = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.treeleaf.anydone.entities.MisleadingResponse} returns this
 */
proto.treeleaf.anydone.entities.MisleadingResponse.prototype.setScore = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


goog.object.extend(exports, proto.treeleaf.anydone.entities);
