// source: pa_bot.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var ticket_pb = require('./ticket_pb.js');
goog.object.extend(proto, ticket_pb);
var calendar_pb = require('./calendar_pb.js');
goog.object.extend(proto, calendar_pb);
var user_pb = require('./user_pb.js');
goog.object.extend(proto, user_pb);
var rtc_pb = require('./rtc_pb.js');
goog.object.extend(proto, rtc_pb);
goog.exportSymbol('proto.treeleaf.anydone.entities.PaBotRequest', null, global);
goog.exportSymbol('proto.treeleaf.anydone.entities.PaBotResponse', null, global);
goog.exportSymbol('proto.treeleaf.anydone.entities.PaBotResponse.PaBotAction', null, global);
goog.exportSymbol('proto.treeleaf.anydone.entities.PaBotResponseType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.treeleaf.anydone.entities.PaBotRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.treeleaf.anydone.entities.PaBotRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.treeleaf.anydone.entities.PaBotRequest.displayName = 'proto.treeleaf.anydone.entities.PaBotRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.treeleaf.anydone.entities.PaBotResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.treeleaf.anydone.entities.PaBotResponse.repeatedFields_, null);
};
goog.inherits(proto.treeleaf.anydone.entities.PaBotResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.treeleaf.anydone.entities.PaBotResponse.displayName = 'proto.treeleaf.anydone.entities.PaBotResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.treeleaf.anydone.entities.PaBotRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.treeleaf.anydone.entities.PaBotRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.treeleaf.anydone.entities.PaBotRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.PaBotRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    query: jspb.Message.getFieldWithDefault(msg, 1, ""),
    timezone: jspb.Message.getFieldWithDefault(msg, 2, ""),
    token: jspb.Message.getFieldWithDefault(msg, 3, ""),
    clientid: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.treeleaf.anydone.entities.PaBotRequest}
 */
proto.treeleaf.anydone.entities.PaBotRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.treeleaf.anydone.entities.PaBotRequest;
  return proto.treeleaf.anydone.entities.PaBotRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.treeleaf.anydone.entities.PaBotRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.treeleaf.anydone.entities.PaBotRequest}
 */
proto.treeleaf.anydone.entities.PaBotRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setQuery(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTimezone(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setToken(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setClientid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.treeleaf.anydone.entities.PaBotRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.treeleaf.anydone.entities.PaBotRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.treeleaf.anydone.entities.PaBotRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.PaBotRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getQuery();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTimezone();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getToken();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getClientid();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional string query = 1;
 * @return {string}
 */
proto.treeleaf.anydone.entities.PaBotRequest.prototype.getQuery = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.PaBotRequest} returns this
 */
proto.treeleaf.anydone.entities.PaBotRequest.prototype.setQuery = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string timezone = 2;
 * @return {string}
 */
proto.treeleaf.anydone.entities.PaBotRequest.prototype.getTimezone = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.PaBotRequest} returns this
 */
proto.treeleaf.anydone.entities.PaBotRequest.prototype.setTimezone = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string token = 3;
 * @return {string}
 */
proto.treeleaf.anydone.entities.PaBotRequest.prototype.getToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.PaBotRequest} returns this
 */
proto.treeleaf.anydone.entities.PaBotRequest.prototype.setToken = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string clientId = 4;
 * @return {string}
 */
proto.treeleaf.anydone.entities.PaBotRequest.prototype.getClientid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.PaBotRequest} returns this
 */
proto.treeleaf.anydone.entities.PaBotRequest.prototype.setClientid = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.treeleaf.anydone.entities.PaBotResponse.repeatedFields_ = [8,11];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.treeleaf.anydone.entities.PaBotResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.treeleaf.anydone.entities.PaBotResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.treeleaf.anydone.entities.PaBotResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.PaBotResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    senderid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    timestamp: jspb.Message.getFieldWithDefault(msg, 3, 0),
    action: jspb.Message.getFieldWithDefault(msg, 4, 0),
    botreply: jspb.Message.getFieldWithDefault(msg, 5, ""),
    ticket: (f = msg.getTicket()) && ticket_pb.Ticket.toObject(includeInstance, f),
    meet: (f = msg.getMeet()) && calendar_pb.Meet.toObject(includeInstance, f),
    accountList: jspb.Message.toObjectList(msg.getAccountList(),
    user_pb.Account.toObject, includeInstance),
    url: jspb.Message.getFieldWithDefault(msg, 9, ""),
    scheduledat: jspb.Message.getFieldWithDefault(msg, 10, 0),
    timeslotList: jspb.Message.toObjectList(msg.getTimeslotList(),
    calendar_pb.MeetTimeslot.toObject, includeInstance),
    from: jspb.Message.getFieldWithDefault(msg, 12, 0),
    to: jspb.Message.getFieldWithDefault(msg, 13, 0),
    rtcmessage: (f = msg.getRtcmessage()) && rtc_pb.RtcMessage.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.treeleaf.anydone.entities.PaBotResponse}
 */
proto.treeleaf.anydone.entities.PaBotResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.treeleaf.anydone.entities.PaBotResponse;
  return proto.treeleaf.anydone.entities.PaBotResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.treeleaf.anydone.entities.PaBotResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.treeleaf.anydone.entities.PaBotResponse}
 */
proto.treeleaf.anydone.entities.PaBotResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSenderid(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestamp(value);
      break;
    case 4:
      var value = /** @type {!proto.treeleaf.anydone.entities.PaBotResponse.PaBotAction} */ (reader.readEnum());
      msg.setAction(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setBotreply(value);
      break;
    case 6:
      var value = new ticket_pb.Ticket;
      reader.readMessage(value,ticket_pb.Ticket.deserializeBinaryFromReader);
      msg.setTicket(value);
      break;
    case 7:
      var value = new calendar_pb.Meet;
      reader.readMessage(value,calendar_pb.Meet.deserializeBinaryFromReader);
      msg.setMeet(value);
      break;
    case 8:
      var value = new user_pb.Account;
      reader.readMessage(value,user_pb.Account.deserializeBinaryFromReader);
      msg.addAccount(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setScheduledat(value);
      break;
    case 11:
      var value = new calendar_pb.MeetTimeslot;
      reader.readMessage(value,calendar_pb.MeetTimeslot.deserializeBinaryFromReader);
      msg.addTimeslot(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setFrom(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTo(value);
      break;
    case 14:
      var value = new rtc_pb.RtcMessage;
      reader.readMessage(value,rtc_pb.RtcMessage.deserializeBinaryFromReader);
      msg.setRtcmessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.treeleaf.anydone.entities.PaBotResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.treeleaf.anydone.entities.PaBotResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.treeleaf.anydone.entities.PaBotResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.PaBotResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSenderid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getAction();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getBotreply();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getTicket();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      ticket_pb.Ticket.serializeBinaryToWriter
    );
  }
  f = message.getMeet();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      calendar_pb.Meet.serializeBinaryToWriter
    );
  }
  f = message.getAccountList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      8,
      f,
      user_pb.Account.serializeBinaryToWriter
    );
  }
  f = message.getUrl();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getScheduledat();
  if (f !== 0) {
    writer.writeInt64(
      10,
      f
    );
  }
  f = message.getTimeslotList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      11,
      f,
      calendar_pb.MeetTimeslot.serializeBinaryToWriter
    );
  }
  f = message.getFrom();
  if (f !== 0) {
    writer.writeInt64(
      12,
      f
    );
  }
  f = message.getTo();
  if (f !== 0) {
    writer.writeInt64(
      13,
      f
    );
  }
  f = message.getRtcmessage();
  if (f != null) {
    writer.writeMessage(
      14,
      f,
      rtc_pb.RtcMessage.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.treeleaf.anydone.entities.PaBotResponse.PaBotAction = {
  UNKNOWN_ACTION: 0,
  CREATE_TICKET_ACTION: 1,
  CREATE_MEET_ACTION: 2,
  CALL_ACTION: 3,
  WEATHER_DETAIL_ACTION: 4,
  MESSAGE_ACTION: 5,
  REMINDER_ACTION: 6,
  FILE_SEARCH_ACTION: 7,
  TODO_LIST_ACTION: 8,
  DEFAULT_ACTION: 9,
  GREET_ACTION: 10,
  GOODBYE_ACTION: 11,
  DISPLAY_MEETING_PA: 12,
  TODO_CREATE_ACTION: 13,
  TICKET_DISPLAY_ACTION: 14,
  DISPLAY_REMINDER_ACTION: 15,
  REPLY_REMINDER_NOTIFICATION: 16
};

/**
 * optional string id = 1;
 * @return {string}
 */
proto.treeleaf.anydone.entities.PaBotResponse.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.PaBotResponse} returns this
 */
proto.treeleaf.anydone.entities.PaBotResponse.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string senderId = 2;
 * @return {string}
 */
proto.treeleaf.anydone.entities.PaBotResponse.prototype.getSenderid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.PaBotResponse} returns this
 */
proto.treeleaf.anydone.entities.PaBotResponse.prototype.setSenderid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int64 timestamp = 3;
 * @return {number}
 */
proto.treeleaf.anydone.entities.PaBotResponse.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.treeleaf.anydone.entities.PaBotResponse} returns this
 */
proto.treeleaf.anydone.entities.PaBotResponse.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional PaBotAction action = 4;
 * @return {!proto.treeleaf.anydone.entities.PaBotResponse.PaBotAction}
 */
proto.treeleaf.anydone.entities.PaBotResponse.prototype.getAction = function() {
  return /** @type {!proto.treeleaf.anydone.entities.PaBotResponse.PaBotAction} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.treeleaf.anydone.entities.PaBotResponse.PaBotAction} value
 * @return {!proto.treeleaf.anydone.entities.PaBotResponse} returns this
 */
proto.treeleaf.anydone.entities.PaBotResponse.prototype.setAction = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional string botReply = 5;
 * @return {string}
 */
proto.treeleaf.anydone.entities.PaBotResponse.prototype.getBotreply = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.PaBotResponse} returns this
 */
proto.treeleaf.anydone.entities.PaBotResponse.prototype.setBotreply = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional Ticket ticket = 6;
 * @return {?proto.treeleaf.anydone.entities.Ticket}
 */
proto.treeleaf.anydone.entities.PaBotResponse.prototype.getTicket = function() {
  return /** @type{?proto.treeleaf.anydone.entities.Ticket} */ (
    jspb.Message.getWrapperField(this, ticket_pb.Ticket, 6));
};


/**
 * @param {?proto.treeleaf.anydone.entities.Ticket|undefined} value
 * @return {!proto.treeleaf.anydone.entities.PaBotResponse} returns this
*/
proto.treeleaf.anydone.entities.PaBotResponse.prototype.setTicket = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.entities.PaBotResponse} returns this
 */
proto.treeleaf.anydone.entities.PaBotResponse.prototype.clearTicket = function() {
  return this.setTicket(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.entities.PaBotResponse.prototype.hasTicket = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional Meet meet = 7;
 * @return {?proto.treeleaf.anydone.entities.Meet}
 */
proto.treeleaf.anydone.entities.PaBotResponse.prototype.getMeet = function() {
  return /** @type{?proto.treeleaf.anydone.entities.Meet} */ (
    jspb.Message.getWrapperField(this, calendar_pb.Meet, 7));
};


/**
 * @param {?proto.treeleaf.anydone.entities.Meet|undefined} value
 * @return {!proto.treeleaf.anydone.entities.PaBotResponse} returns this
*/
proto.treeleaf.anydone.entities.PaBotResponse.prototype.setMeet = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.entities.PaBotResponse} returns this
 */
proto.treeleaf.anydone.entities.PaBotResponse.prototype.clearMeet = function() {
  return this.setMeet(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.entities.PaBotResponse.prototype.hasMeet = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * repeated Account account = 8;
 * @return {!Array<!proto.treeleaf.anydone.entities.Account>}
 */
proto.treeleaf.anydone.entities.PaBotResponse.prototype.getAccountList = function() {
  return /** @type{!Array<!proto.treeleaf.anydone.entities.Account>} */ (
    jspb.Message.getRepeatedWrapperField(this, user_pb.Account, 8));
};


/**
 * @param {!Array<!proto.treeleaf.anydone.entities.Account>} value
 * @return {!proto.treeleaf.anydone.entities.PaBotResponse} returns this
*/
proto.treeleaf.anydone.entities.PaBotResponse.prototype.setAccountList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 8, value);
};


/**
 * @param {!proto.treeleaf.anydone.entities.Account=} opt_value
 * @param {number=} opt_index
 * @return {!proto.treeleaf.anydone.entities.Account}
 */
proto.treeleaf.anydone.entities.PaBotResponse.prototype.addAccount = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 8, opt_value, proto.treeleaf.anydone.entities.Account, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.treeleaf.anydone.entities.PaBotResponse} returns this
 */
proto.treeleaf.anydone.entities.PaBotResponse.prototype.clearAccountList = function() {
  return this.setAccountList([]);
};


/**
 * optional string url = 9;
 * @return {string}
 */
proto.treeleaf.anydone.entities.PaBotResponse.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.PaBotResponse} returns this
 */
proto.treeleaf.anydone.entities.PaBotResponse.prototype.setUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional int64 scheduledat = 10;
 * @return {number}
 */
proto.treeleaf.anydone.entities.PaBotResponse.prototype.getScheduledat = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.treeleaf.anydone.entities.PaBotResponse} returns this
 */
proto.treeleaf.anydone.entities.PaBotResponse.prototype.setScheduledat = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * repeated MeetTimeslot timeslot = 11;
 * @return {!Array<!proto.treeleaf.anydone.entities.MeetTimeslot>}
 */
proto.treeleaf.anydone.entities.PaBotResponse.prototype.getTimeslotList = function() {
  return /** @type{!Array<!proto.treeleaf.anydone.entities.MeetTimeslot>} */ (
    jspb.Message.getRepeatedWrapperField(this, calendar_pb.MeetTimeslot, 11));
};


/**
 * @param {!Array<!proto.treeleaf.anydone.entities.MeetTimeslot>} value
 * @return {!proto.treeleaf.anydone.entities.PaBotResponse} returns this
*/
proto.treeleaf.anydone.entities.PaBotResponse.prototype.setTimeslotList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 11, value);
};


/**
 * @param {!proto.treeleaf.anydone.entities.MeetTimeslot=} opt_value
 * @param {number=} opt_index
 * @return {!proto.treeleaf.anydone.entities.MeetTimeslot}
 */
proto.treeleaf.anydone.entities.PaBotResponse.prototype.addTimeslot = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 11, opt_value, proto.treeleaf.anydone.entities.MeetTimeslot, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.treeleaf.anydone.entities.PaBotResponse} returns this
 */
proto.treeleaf.anydone.entities.PaBotResponse.prototype.clearTimeslotList = function() {
  return this.setTimeslotList([]);
};


/**
 * optional int64 from = 12;
 * @return {number}
 */
proto.treeleaf.anydone.entities.PaBotResponse.prototype.getFrom = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.treeleaf.anydone.entities.PaBotResponse} returns this
 */
proto.treeleaf.anydone.entities.PaBotResponse.prototype.setFrom = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * optional int64 to = 13;
 * @return {number}
 */
proto.treeleaf.anydone.entities.PaBotResponse.prototype.getTo = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.treeleaf.anydone.entities.PaBotResponse} returns this
 */
proto.treeleaf.anydone.entities.PaBotResponse.prototype.setTo = function(value) {
  return jspb.Message.setProto3IntField(this, 13, value);
};


/**
 * optional RtcMessage rtcMessage = 14;
 * @return {?proto.treeleaf.anydone.entities.RtcMessage}
 */
proto.treeleaf.anydone.entities.PaBotResponse.prototype.getRtcmessage = function() {
  return /** @type{?proto.treeleaf.anydone.entities.RtcMessage} */ (
    jspb.Message.getWrapperField(this, rtc_pb.RtcMessage, 14));
};


/**
 * @param {?proto.treeleaf.anydone.entities.RtcMessage|undefined} value
 * @return {!proto.treeleaf.anydone.entities.PaBotResponse} returns this
*/
proto.treeleaf.anydone.entities.PaBotResponse.prototype.setRtcmessage = function(value) {
  return jspb.Message.setWrapperField(this, 14, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.entities.PaBotResponse} returns this
 */
proto.treeleaf.anydone.entities.PaBotResponse.prototype.clearRtcmessage = function() {
  return this.setRtcmessage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.entities.PaBotResponse.prototype.hasRtcmessage = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * @enum {number}
 */
proto.treeleaf.anydone.entities.PaBotResponseType = {
  UNKNOWN_PA_BOT_RESPONSE_TYPE: 0,
  CONVERSATION_PA_BOT_RESPONSE: 1,
  PA_BOT_RESPONSE: 2
};

goog.object.extend(exports, proto.treeleaf.anydone.entities);
