// source: paraphrase.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.treeleaf.anydone.entities.ParaphraseGenerateRequest', null, global);
goog.exportSymbol('proto.treeleaf.anydone.entities.ParaphraseGenerateResponse', null, global);
goog.exportSymbol('proto.treeleaf.anydone.entities.ParaphraseTexts', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.treeleaf.anydone.entities.ParaphraseGenerateRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.treeleaf.anydone.entities.ParaphraseGenerateRequest.repeatedFields_, null);
};
goog.inherits(proto.treeleaf.anydone.entities.ParaphraseGenerateRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.treeleaf.anydone.entities.ParaphraseGenerateRequest.displayName = 'proto.treeleaf.anydone.entities.ParaphraseGenerateRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.treeleaf.anydone.entities.ParaphraseTexts = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.treeleaf.anydone.entities.ParaphraseTexts, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.treeleaf.anydone.entities.ParaphraseTexts.displayName = 'proto.treeleaf.anydone.entities.ParaphraseTexts';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.treeleaf.anydone.entities.ParaphraseGenerateResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.treeleaf.anydone.entities.ParaphraseGenerateResponse.repeatedFields_, null);
};
goog.inherits(proto.treeleaf.anydone.entities.ParaphraseGenerateResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.treeleaf.anydone.entities.ParaphraseGenerateResponse.displayName = 'proto.treeleaf.anydone.entities.ParaphraseGenerateResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.treeleaf.anydone.entities.ParaphraseGenerateRequest.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.treeleaf.anydone.entities.ParaphraseGenerateRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.treeleaf.anydone.entities.ParaphraseGenerateRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.treeleaf.anydone.entities.ParaphraseGenerateRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.ParaphraseGenerateRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    textsList: jspb.Message.toObjectList(msg.getTextsList(),
    proto.treeleaf.anydone.entities.ParaphraseTexts.toObject, includeInstance),
    thresholdnumber: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.treeleaf.anydone.entities.ParaphraseGenerateRequest}
 */
proto.treeleaf.anydone.entities.ParaphraseGenerateRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.treeleaf.anydone.entities.ParaphraseGenerateRequest;
  return proto.treeleaf.anydone.entities.ParaphraseGenerateRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.treeleaf.anydone.entities.ParaphraseGenerateRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.treeleaf.anydone.entities.ParaphraseGenerateRequest}
 */
proto.treeleaf.anydone.entities.ParaphraseGenerateRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.treeleaf.anydone.entities.ParaphraseTexts;
      reader.readMessage(value,proto.treeleaf.anydone.entities.ParaphraseTexts.deserializeBinaryFromReader);
      msg.addTexts(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setThresholdnumber(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.treeleaf.anydone.entities.ParaphraseGenerateRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.treeleaf.anydone.entities.ParaphraseGenerateRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.treeleaf.anydone.entities.ParaphraseGenerateRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.ParaphraseGenerateRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTextsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.treeleaf.anydone.entities.ParaphraseTexts.serializeBinaryToWriter
    );
  }
  f = message.getThresholdnumber();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
};


/**
 * repeated ParaphraseTexts texts = 1;
 * @return {!Array<!proto.treeleaf.anydone.entities.ParaphraseTexts>}
 */
proto.treeleaf.anydone.entities.ParaphraseGenerateRequest.prototype.getTextsList = function() {
  return /** @type{!Array<!proto.treeleaf.anydone.entities.ParaphraseTexts>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.treeleaf.anydone.entities.ParaphraseTexts, 1));
};


/**
 * @param {!Array<!proto.treeleaf.anydone.entities.ParaphraseTexts>} value
 * @return {!proto.treeleaf.anydone.entities.ParaphraseGenerateRequest} returns this
*/
proto.treeleaf.anydone.entities.ParaphraseGenerateRequest.prototype.setTextsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.treeleaf.anydone.entities.ParaphraseTexts=} opt_value
 * @param {number=} opt_index
 * @return {!proto.treeleaf.anydone.entities.ParaphraseTexts}
 */
proto.treeleaf.anydone.entities.ParaphraseGenerateRequest.prototype.addTexts = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.treeleaf.anydone.entities.ParaphraseTexts, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.treeleaf.anydone.entities.ParaphraseGenerateRequest} returns this
 */
proto.treeleaf.anydone.entities.ParaphraseGenerateRequest.prototype.clearTextsList = function() {
  return this.setTextsList([]);
};


/**
 * optional int64 thresholdNumber = 2;
 * @return {number}
 */
proto.treeleaf.anydone.entities.ParaphraseGenerateRequest.prototype.getThresholdnumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.treeleaf.anydone.entities.ParaphraseGenerateRequest} returns this
 */
proto.treeleaf.anydone.entities.ParaphraseGenerateRequest.prototype.setThresholdnumber = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.treeleaf.anydone.entities.ParaphraseTexts.prototype.toObject = function(opt_includeInstance) {
  return proto.treeleaf.anydone.entities.ParaphraseTexts.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.treeleaf.anydone.entities.ParaphraseTexts} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.ParaphraseTexts.toObject = function(includeInstance, msg) {
  var f, obj = {
    inputtext: jspb.Message.getFieldWithDefault(msg, 1, ""),
    originaltext: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.treeleaf.anydone.entities.ParaphraseTexts}
 */
proto.treeleaf.anydone.entities.ParaphraseTexts.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.treeleaf.anydone.entities.ParaphraseTexts;
  return proto.treeleaf.anydone.entities.ParaphraseTexts.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.treeleaf.anydone.entities.ParaphraseTexts} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.treeleaf.anydone.entities.ParaphraseTexts}
 */
proto.treeleaf.anydone.entities.ParaphraseTexts.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setInputtext(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setOriginaltext(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.treeleaf.anydone.entities.ParaphraseTexts.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.treeleaf.anydone.entities.ParaphraseTexts.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.treeleaf.anydone.entities.ParaphraseTexts} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.ParaphraseTexts.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInputtext();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOriginaltext();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string inputText = 1;
 * @return {string}
 */
proto.treeleaf.anydone.entities.ParaphraseTexts.prototype.getInputtext = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.ParaphraseTexts} returns this
 */
proto.treeleaf.anydone.entities.ParaphraseTexts.prototype.setInputtext = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string originalText = 2;
 * @return {string}
 */
proto.treeleaf.anydone.entities.ParaphraseTexts.prototype.getOriginaltext = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.ParaphraseTexts} returns this
 */
proto.treeleaf.anydone.entities.ParaphraseTexts.prototype.setOriginaltext = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.treeleaf.anydone.entities.ParaphraseGenerateResponse.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.treeleaf.anydone.entities.ParaphraseGenerateResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.treeleaf.anydone.entities.ParaphraseGenerateResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.treeleaf.anydone.entities.ParaphraseGenerateResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.ParaphraseGenerateResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    inputtext: jspb.Message.getFieldWithDefault(msg, 1, ""),
    paraphrasesList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
    originaltext: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.treeleaf.anydone.entities.ParaphraseGenerateResponse}
 */
proto.treeleaf.anydone.entities.ParaphraseGenerateResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.treeleaf.anydone.entities.ParaphraseGenerateResponse;
  return proto.treeleaf.anydone.entities.ParaphraseGenerateResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.treeleaf.anydone.entities.ParaphraseGenerateResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.treeleaf.anydone.entities.ParaphraseGenerateResponse}
 */
proto.treeleaf.anydone.entities.ParaphraseGenerateResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setInputtext(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addParaphrases(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setOriginaltext(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.treeleaf.anydone.entities.ParaphraseGenerateResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.treeleaf.anydone.entities.ParaphraseGenerateResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.treeleaf.anydone.entities.ParaphraseGenerateResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.ParaphraseGenerateResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInputtext();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getParaphrasesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getOriginaltext();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string inputText = 1;
 * @return {string}
 */
proto.treeleaf.anydone.entities.ParaphraseGenerateResponse.prototype.getInputtext = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.ParaphraseGenerateResponse} returns this
 */
proto.treeleaf.anydone.entities.ParaphraseGenerateResponse.prototype.setInputtext = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated string paraphrases = 2;
 * @return {!Array<string>}
 */
proto.treeleaf.anydone.entities.ParaphraseGenerateResponse.prototype.getParaphrasesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.treeleaf.anydone.entities.ParaphraseGenerateResponse} returns this
 */
proto.treeleaf.anydone.entities.ParaphraseGenerateResponse.prototype.setParaphrasesList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.treeleaf.anydone.entities.ParaphraseGenerateResponse} returns this
 */
proto.treeleaf.anydone.entities.ParaphraseGenerateResponse.prototype.addParaphrases = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.treeleaf.anydone.entities.ParaphraseGenerateResponse} returns this
 */
proto.treeleaf.anydone.entities.ParaphraseGenerateResponse.prototype.clearParaphrasesList = function() {
  return this.setParaphrasesList([]);
};


/**
 * optional string originalText = 3;
 * @return {string}
 */
proto.treeleaf.anydone.entities.ParaphraseGenerateResponse.prototype.getOriginaltext = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.ParaphraseGenerateResponse} returns this
 */
proto.treeleaf.anydone.entities.ParaphraseGenerateResponse.prototype.setOriginaltext = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


goog.object.extend(exports, proto.treeleaf.anydone.entities);
