// source: project_rpc.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var auth_pb = require('./auth_pb.js');
goog.object.extend(proto, auth_pb);
var treeleaf_pb = require('./treeleaf_pb.js');
goog.object.extend(proto, treeleaf_pb);
var project_pb = require('./project_pb.js');
goog.object.extend(proto, project_pb);
var service_pb = require('./service_pb.js');
goog.object.extend(proto, service_pb);
goog.exportSymbol('proto.treeleaf.anydone.rpc.ProjectBaseRequest', null, global);
goog.exportSymbol('proto.treeleaf.anydone.rpc.ProjectBaseResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.treeleaf.anydone.rpc.ProjectBaseRequest.repeatedFields_, null);
};
goog.inherits(proto.treeleaf.anydone.rpc.ProjectBaseRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.treeleaf.anydone.rpc.ProjectBaseRequest.displayName = 'proto.treeleaf.anydone.rpc.ProjectBaseRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.treeleaf.anydone.rpc.ProjectBaseResponse.repeatedFields_, null);
};
goog.inherits(proto.treeleaf.anydone.rpc.ProjectBaseResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.treeleaf.anydone.rpc.ProjectBaseResponse.displayName = 'proto.treeleaf.anydone.rpc.ProjectBaseResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.treeleaf.anydone.rpc.ProjectBaseRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.treeleaf.anydone.rpc.ProjectBaseRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    refid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    stringvalue: jspb.Message.getFieldWithDefault(msg, 2, ""),
    stringvaluesList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    intvalue: jspb.Message.getFieldWithDefault(msg, 4, 0),
    longvalue: jspb.Message.getFieldWithDefault(msg, 5, 0),
    boolvalue: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    doublevalue: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
    authorization: (f = msg.getAuthorization()) && auth_pb.Authorization.toObject(includeInstance, f),
    debug: (f = msg.getDebug()) && treeleaf_pb.Debug.toObject(includeInstance, f),
    project: (f = msg.getProject()) && project_pb.Project.toObject(includeInstance, f),
    category: (f = msg.getCategory()) && service_pb.ServiceCategory.toObject(includeInstance, f),
    filter: (f = msg.getFilter()) && project_pb.ProjectFilter.toObject(includeInstance, f),
    validationrequest: (f = msg.getValidationrequest()) && project_pb.ProjectValidationRequest.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseRequest}
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.treeleaf.anydone.rpc.ProjectBaseRequest;
  return proto.treeleaf.anydone.rpc.ProjectBaseRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.treeleaf.anydone.rpc.ProjectBaseRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseRequest}
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRefid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setStringvalue(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addStringvalues(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setIntvalue(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLongvalue(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setBoolvalue(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDoublevalue(value);
      break;
    case 8:
      var value = new auth_pb.Authorization;
      reader.readMessage(value,auth_pb.Authorization.deserializeBinaryFromReader);
      msg.setAuthorization(value);
      break;
    case 9:
      var value = new treeleaf_pb.Debug;
      reader.readMessage(value,treeleaf_pb.Debug.deserializeBinaryFromReader);
      msg.setDebug(value);
      break;
    case 10:
      var value = new project_pb.Project;
      reader.readMessage(value,project_pb.Project.deserializeBinaryFromReader);
      msg.setProject(value);
      break;
    case 11:
      var value = new service_pb.ServiceCategory;
      reader.readMessage(value,service_pb.ServiceCategory.deserializeBinaryFromReader);
      msg.setCategory(value);
      break;
    case 12:
      var value = new project_pb.ProjectFilter;
      reader.readMessage(value,project_pb.ProjectFilter.deserializeBinaryFromReader);
      msg.setFilter(value);
      break;
    case 13:
      var value = new project_pb.ProjectValidationRequest;
      reader.readMessage(value,project_pb.ProjectValidationRequest.deserializeBinaryFromReader);
      msg.setValidationrequest(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.treeleaf.anydone.rpc.ProjectBaseRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.treeleaf.anydone.rpc.ProjectBaseRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRefid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStringvalue();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getStringvaluesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getIntvalue();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getLongvalue();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getBoolvalue();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getDoublevalue();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getAuthorization();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      auth_pb.Authorization.serializeBinaryToWriter
    );
  }
  f = message.getDebug();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      treeleaf_pb.Debug.serializeBinaryToWriter
    );
  }
  f = message.getProject();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      project_pb.Project.serializeBinaryToWriter
    );
  }
  f = message.getCategory();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      service_pb.ServiceCategory.serializeBinaryToWriter
    );
  }
  f = message.getFilter();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      project_pb.ProjectFilter.serializeBinaryToWriter
    );
  }
  f = message.getValidationrequest();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      project_pb.ProjectValidationRequest.serializeBinaryToWriter
    );
  }
};


/**
 * optional string refId = 1;
 * @return {string}
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.getRefid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.setRefid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string stringValue = 2;
 * @return {string}
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.getStringvalue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.setStringvalue = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated string stringValues = 3;
 * @return {!Array<string>}
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.getStringvaluesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.setStringvaluesList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.addStringvalues = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.clearStringvaluesList = function() {
  return this.setStringvaluesList([]);
};


/**
 * optional int32 intValue = 4;
 * @return {number}
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.getIntvalue = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.setIntvalue = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int64 longValue = 5;
 * @return {number}
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.getLongvalue = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.setLongvalue = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional bool boolValue = 6;
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.getBoolvalue = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.setBoolvalue = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional bool doubleValue = 7;
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.getDoublevalue = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.setDoublevalue = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * optional treeleaf.anydone.entities.Authorization authorization = 8;
 * @return {?proto.treeleaf.anydone.entities.Authorization}
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.getAuthorization = function() {
  return /** @type{?proto.treeleaf.anydone.entities.Authorization} */ (
    jspb.Message.getWrapperField(this, auth_pb.Authorization, 8));
};


/**
 * @param {?proto.treeleaf.anydone.entities.Authorization|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseRequest} returns this
*/
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.setAuthorization = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.clearAuthorization = function() {
  return this.setAuthorization(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.hasAuthorization = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional treeleaf.protos.Debug debug = 9;
 * @return {?proto.treeleaf.protos.Debug}
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.getDebug = function() {
  return /** @type{?proto.treeleaf.protos.Debug} */ (
    jspb.Message.getWrapperField(this, treeleaf_pb.Debug, 9));
};


/**
 * @param {?proto.treeleaf.protos.Debug|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseRequest} returns this
*/
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.setDebug = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.clearDebug = function() {
  return this.setDebug(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.hasDebug = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional treeleaf.anydone.entities.Project project = 10;
 * @return {?proto.treeleaf.anydone.entities.Project}
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.getProject = function() {
  return /** @type{?proto.treeleaf.anydone.entities.Project} */ (
    jspb.Message.getWrapperField(this, project_pb.Project, 10));
};


/**
 * @param {?proto.treeleaf.anydone.entities.Project|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseRequest} returns this
*/
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.setProject = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.clearProject = function() {
  return this.setProject(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.hasProject = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional treeleaf.anydone.entities.ServiceCategory category = 11;
 * @return {?proto.treeleaf.anydone.entities.ServiceCategory}
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.getCategory = function() {
  return /** @type{?proto.treeleaf.anydone.entities.ServiceCategory} */ (
    jspb.Message.getWrapperField(this, service_pb.ServiceCategory, 11));
};


/**
 * @param {?proto.treeleaf.anydone.entities.ServiceCategory|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseRequest} returns this
*/
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.setCategory = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.clearCategory = function() {
  return this.setCategory(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.hasCategory = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional treeleaf.anydone.entities.ProjectFilter filter = 12;
 * @return {?proto.treeleaf.anydone.entities.ProjectFilter}
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.getFilter = function() {
  return /** @type{?proto.treeleaf.anydone.entities.ProjectFilter} */ (
    jspb.Message.getWrapperField(this, project_pb.ProjectFilter, 12));
};


/**
 * @param {?proto.treeleaf.anydone.entities.ProjectFilter|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseRequest} returns this
*/
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.setFilter = function(value) {
  return jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.clearFilter = function() {
  return this.setFilter(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.hasFilter = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional treeleaf.anydone.entities.ProjectValidationRequest validationRequest = 13;
 * @return {?proto.treeleaf.anydone.entities.ProjectValidationRequest}
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.getValidationrequest = function() {
  return /** @type{?proto.treeleaf.anydone.entities.ProjectValidationRequest} */ (
    jspb.Message.getWrapperField(this, project_pb.ProjectValidationRequest, 13));
};


/**
 * @param {?proto.treeleaf.anydone.entities.ProjectValidationRequest|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseRequest} returns this
*/
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.setValidationrequest = function(value) {
  return jspb.Message.setWrapperField(this, 13, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseRequest} returns this
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.clearValidationrequest = function() {
  return this.setValidationrequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.ProjectBaseRequest.prototype.hasValidationrequest = function() {
  return jspb.Message.getField(this, 13) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.repeatedFields_ = [48];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.treeleaf.anydone.rpc.ProjectBaseResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.treeleaf.anydone.rpc.ProjectBaseResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    error: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    msg: jspb.Message.getFieldWithDefault(msg, 2, ""),
    errorcode: jspb.Message.getFieldWithDefault(msg, 3, 0),
    success: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    timestamp: jspb.Message.getFieldWithDefault(msg, 5, 0),
    debug: (f = msg.getDebug()) && treeleaf_pb.Debug.toObject(includeInstance, f),
    refid: jspb.Message.getFieldWithDefault(msg, 7, ""),
    authorization: (f = msg.getAuthorization()) && auth_pb.Authorization.toObject(includeInstance, f),
    project: (f = msg.getProject()) && project_pb.Project.toObject(includeInstance, f),
    category: (f = msg.getCategory()) && service_pb.ServiceCategory.toObject(includeInstance, f),
    validationresponse: (f = msg.getValidationresponse()) && project_pb.ProjectValidationResponse.toObject(includeInstance, f),
    projectsList: jspb.Message.toObjectList(msg.getProjectsList(),
    project_pb.Project.toObject, includeInstance),
    cursor: (f = msg.getCursor()) && treeleaf_pb.Cursor.toObject(includeInstance, f),
    count: jspb.Message.getFieldWithDefault(msg, 12, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseResponse}
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.treeleaf.anydone.rpc.ProjectBaseResponse;
  return proto.treeleaf.anydone.rpc.ProjectBaseResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.treeleaf.anydone.rpc.ProjectBaseResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseResponse}
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setError(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMsg(value);
      break;
    case 3:
      var value = /** @type {!proto.treeleaf.protos.ErrorCode} */ (reader.readEnum());
      msg.setErrorcode(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSuccess(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestamp(value);
      break;
    case 6:
      var value = new treeleaf_pb.Debug;
      reader.readMessage(value,treeleaf_pb.Debug.deserializeBinaryFromReader);
      msg.setDebug(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setRefid(value);
      break;
    case 8:
      var value = new auth_pb.Authorization;
      reader.readMessage(value,auth_pb.Authorization.deserializeBinaryFromReader);
      msg.setAuthorization(value);
      break;
    case 9:
      var value = new project_pb.Project;
      reader.readMessage(value,project_pb.Project.deserializeBinaryFromReader);
      msg.setProject(value);
      break;
    case 10:
      var value = new service_pb.ServiceCategory;
      reader.readMessage(value,service_pb.ServiceCategory.deserializeBinaryFromReader);
      msg.setCategory(value);
      break;
    case 11:
      var value = new project_pb.ProjectValidationResponse;
      reader.readMessage(value,project_pb.ProjectValidationResponse.deserializeBinaryFromReader);
      msg.setValidationresponse(value);
      break;
    case 48:
      var value = new project_pb.Project;
      reader.readMessage(value,project_pb.Project.deserializeBinaryFromReader);
      msg.addProjects(value);
      break;
    case 49:
      var value = new treeleaf_pb.Cursor;
      reader.readMessage(value,treeleaf_pb.Cursor.deserializeBinaryFromReader);
      msg.setCursor(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCount(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.treeleaf.anydone.rpc.ProjectBaseResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.treeleaf.anydone.rpc.ProjectBaseResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getError();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getMsg();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getErrorcode();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getSuccess();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getDebug();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      treeleaf_pb.Debug.serializeBinaryToWriter
    );
  }
  f = message.getRefid();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getAuthorization();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      auth_pb.Authorization.serializeBinaryToWriter
    );
  }
  f = message.getProject();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      project_pb.Project.serializeBinaryToWriter
    );
  }
  f = message.getCategory();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      service_pb.ServiceCategory.serializeBinaryToWriter
    );
  }
  f = message.getValidationresponse();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      project_pb.ProjectValidationResponse.serializeBinaryToWriter
    );
  }
  f = message.getProjectsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      48,
      f,
      project_pb.Project.serializeBinaryToWriter
    );
  }
  f = message.getCursor();
  if (f != null) {
    writer.writeMessage(
      49,
      f,
      treeleaf_pb.Cursor.serializeBinaryToWriter
    );
  }
  f = message.getCount();
  if (f !== 0) {
    writer.writeInt64(
      12,
      f
    );
  }
};


/**
 * optional bool error = 1;
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.getError = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.setError = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional string msg = 2;
 * @return {string}
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.getMsg = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.setMsg = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional treeleaf.protos.ErrorCode errorCode = 3;
 * @return {!proto.treeleaf.protos.ErrorCode}
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.getErrorcode = function() {
  return /** @type {!proto.treeleaf.protos.ErrorCode} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.treeleaf.protos.ErrorCode} value
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.setErrorcode = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional bool success = 4;
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.getSuccess = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.setSuccess = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional int64 timestamp = 5;
 * @return {number}
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional treeleaf.protos.Debug debug = 6;
 * @return {?proto.treeleaf.protos.Debug}
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.getDebug = function() {
  return /** @type{?proto.treeleaf.protos.Debug} */ (
    jspb.Message.getWrapperField(this, treeleaf_pb.Debug, 6));
};


/**
 * @param {?proto.treeleaf.protos.Debug|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseResponse} returns this
*/
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.setDebug = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.clearDebug = function() {
  return this.setDebug(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.hasDebug = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional string refId = 7;
 * @return {string}
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.getRefid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.setRefid = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional treeleaf.anydone.entities.Authorization authorization = 8;
 * @return {?proto.treeleaf.anydone.entities.Authorization}
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.getAuthorization = function() {
  return /** @type{?proto.treeleaf.anydone.entities.Authorization} */ (
    jspb.Message.getWrapperField(this, auth_pb.Authorization, 8));
};


/**
 * @param {?proto.treeleaf.anydone.entities.Authorization|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseResponse} returns this
*/
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.setAuthorization = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.clearAuthorization = function() {
  return this.setAuthorization(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.hasAuthorization = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional treeleaf.anydone.entities.Project project = 9;
 * @return {?proto.treeleaf.anydone.entities.Project}
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.getProject = function() {
  return /** @type{?proto.treeleaf.anydone.entities.Project} */ (
    jspb.Message.getWrapperField(this, project_pb.Project, 9));
};


/**
 * @param {?proto.treeleaf.anydone.entities.Project|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseResponse} returns this
*/
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.setProject = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.clearProject = function() {
  return this.setProject(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.hasProject = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional treeleaf.anydone.entities.ServiceCategory category = 10;
 * @return {?proto.treeleaf.anydone.entities.ServiceCategory}
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.getCategory = function() {
  return /** @type{?proto.treeleaf.anydone.entities.ServiceCategory} */ (
    jspb.Message.getWrapperField(this, service_pb.ServiceCategory, 10));
};


/**
 * @param {?proto.treeleaf.anydone.entities.ServiceCategory|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseResponse} returns this
*/
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.setCategory = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.clearCategory = function() {
  return this.setCategory(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.hasCategory = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional treeleaf.anydone.entities.ProjectValidationResponse validationResponse = 11;
 * @return {?proto.treeleaf.anydone.entities.ProjectValidationResponse}
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.getValidationresponse = function() {
  return /** @type{?proto.treeleaf.anydone.entities.ProjectValidationResponse} */ (
    jspb.Message.getWrapperField(this, project_pb.ProjectValidationResponse, 11));
};


/**
 * @param {?proto.treeleaf.anydone.entities.ProjectValidationResponse|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseResponse} returns this
*/
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.setValidationresponse = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.clearValidationresponse = function() {
  return this.setValidationresponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.hasValidationresponse = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * repeated treeleaf.anydone.entities.Project projects = 48;
 * @return {!Array<!proto.treeleaf.anydone.entities.Project>}
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.getProjectsList = function() {
  return /** @type{!Array<!proto.treeleaf.anydone.entities.Project>} */ (
    jspb.Message.getRepeatedWrapperField(this, project_pb.Project, 48));
};


/**
 * @param {!Array<!proto.treeleaf.anydone.entities.Project>} value
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseResponse} returns this
*/
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.setProjectsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 48, value);
};


/**
 * @param {!proto.treeleaf.anydone.entities.Project=} opt_value
 * @param {number=} opt_index
 * @return {!proto.treeleaf.anydone.entities.Project}
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.addProjects = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 48, opt_value, proto.treeleaf.anydone.entities.Project, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.clearProjectsList = function() {
  return this.setProjectsList([]);
};


/**
 * optional treeleaf.protos.Cursor cursor = 49;
 * @return {?proto.treeleaf.protos.Cursor}
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.getCursor = function() {
  return /** @type{?proto.treeleaf.protos.Cursor} */ (
    jspb.Message.getWrapperField(this, treeleaf_pb.Cursor, 49));
};


/**
 * @param {?proto.treeleaf.protos.Cursor|undefined} value
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseResponse} returns this
*/
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.setCursor = function(value) {
  return jspb.Message.setWrapperField(this, 49, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.clearCursor = function() {
  return this.setCursor(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.hasCursor = function() {
  return jspb.Message.getField(this, 49) != null;
};


/**
 * optional int64 count = 12;
 * @return {number}
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.getCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.treeleaf.anydone.rpc.ProjectBaseResponse} returns this
 */
proto.treeleaf.anydone.rpc.ProjectBaseResponse.prototype.setCount = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};


goog.object.extend(exports, proto.treeleaf.anydone.rpc);
