// source: workspace_events.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var user_pb = require('./user_pb.js');
goog.object.extend(proto, user_pb);
goog.exportSymbol('proto.treeleaf.anydone.entities.WorkspaceEvent', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.treeleaf.anydone.entities.WorkspaceEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.treeleaf.anydone.entities.WorkspaceEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.treeleaf.anydone.entities.WorkspaceEvent.displayName = 'proto.treeleaf.anydone.entities.WorkspaceEvent';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.treeleaf.anydone.entities.WorkspaceEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.treeleaf.anydone.entities.WorkspaceEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.treeleaf.anydone.entities.WorkspaceEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.WorkspaceEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    billingaccountid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    serviceproviderprofile: (f = msg.getServiceproviderprofile()) && user_pb.ServiceProviderProfile.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.treeleaf.anydone.entities.WorkspaceEvent}
 */
proto.treeleaf.anydone.entities.WorkspaceEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.treeleaf.anydone.entities.WorkspaceEvent;
  return proto.treeleaf.anydone.entities.WorkspaceEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.treeleaf.anydone.entities.WorkspaceEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.treeleaf.anydone.entities.WorkspaceEvent}
 */
proto.treeleaf.anydone.entities.WorkspaceEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setBillingaccountid(value);
      break;
    case 2:
      var value = new user_pb.ServiceProviderProfile;
      reader.readMessage(value,user_pb.ServiceProviderProfile.deserializeBinaryFromReader);
      msg.setServiceproviderprofile(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.treeleaf.anydone.entities.WorkspaceEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.treeleaf.anydone.entities.WorkspaceEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.treeleaf.anydone.entities.WorkspaceEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.treeleaf.anydone.entities.WorkspaceEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBillingaccountid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getServiceproviderprofile();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      user_pb.ServiceProviderProfile.serializeBinaryToWriter
    );
  }
};


/**
 * optional string billingAccountId = 1;
 * @return {string}
 */
proto.treeleaf.anydone.entities.WorkspaceEvent.prototype.getBillingaccountid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.treeleaf.anydone.entities.WorkspaceEvent} returns this
 */
proto.treeleaf.anydone.entities.WorkspaceEvent.prototype.setBillingaccountid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional ServiceProviderProfile serviceProviderProfile = 2;
 * @return {?proto.treeleaf.anydone.entities.ServiceProviderProfile}
 */
proto.treeleaf.anydone.entities.WorkspaceEvent.prototype.getServiceproviderprofile = function() {
  return /** @type{?proto.treeleaf.anydone.entities.ServiceProviderProfile} */ (
    jspb.Message.getWrapperField(this, user_pb.ServiceProviderProfile, 2));
};


/**
 * @param {?proto.treeleaf.anydone.entities.ServiceProviderProfile|undefined} value
 * @return {!proto.treeleaf.anydone.entities.WorkspaceEvent} returns this
*/
proto.treeleaf.anydone.entities.WorkspaceEvent.prototype.setServiceproviderprofile = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.treeleaf.anydone.entities.WorkspaceEvent} returns this
 */
proto.treeleaf.anydone.entities.WorkspaceEvent.prototype.clearServiceproviderprofile = function() {
  return this.setServiceproviderprofile(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.treeleaf.anydone.entities.WorkspaceEvent.prototype.hasServiceproviderprofile = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.treeleaf.anydone.entities);
